### PR TITLE
Add to cart and other button positioning issue on product view and quick view  #6632

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#6632

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Not working,** when the customer is trying to view any **bundle product** in an **Arabic** locale. Please find the screenshot [Here](https://prnt.sc/4MsixzPR1x26)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Updated for RTL also please check.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Still not working,** if the customer is trying to **search** for any product. Please find the screenshot [Here](https://prnt.sc/d_A7fZsN7d8I)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Please check fixed for searching.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Still not fixed.** the product's image **overriding** the add to cart button, in **Arabic** locale, please find the screenshot [Here](https://prnt.sc/wGCz8fnkJ5NE)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Any **update**?

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
