### PR TITLE
introduce 'checkout.order.orderitem.save.[before/after]' events

### PR DESCRIPTION
**Pull request by thyseus**
I also did a little refactoring to the generateIncrementId() method - please review if i have done this right and if you like this style :)

### CODE REVIEW

**Comment by thyseus** [comment]
Hey, @rahulshukla-webkul 

yes, i indeed was a little bit too quick when refactoring. I adjusted the code and added a very simple unit test.

By the way - do you intend on using phpunit or even codeception in the future for bagisto ?

**Comment by thyseus** [comment]
Yes - removed the type hint. Actually in the future we could think about supporting Order Numbers that contains Letters. Its common to use numbers like "ORD-2019-00023", for example. Needs the "id" column to be varchar(255) though or having a separate order column...

**Comment by bosix** [comment]
@thyseus fyi: there is already an suggestion to introduce codeception. See #1754 for details.

**Comment by thyseus** [comment]
Are there any more changes necessary to get this PR merged ?

**Comment by shubhwebkul** [comment]
Hey @thyseus 
Thanks for your contribution and patience.
Currently, this PR is under review process. We will provide a review asap.

**Pull request merged**
