### PR TITLE
Feature Drag and Drop Image

### PR DESCRIPTION
**Pull request by akathuria289**
## Description
Add Feature Drag and Drop

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The **UI** if upload image can be **enhanced**.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please **resolve** the **conflicts**.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Resolved

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please **improve** the **Select** image **icon**, please find the **screenshot** [Here](https://prnt.sc/nGkfjqmdWwno)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please resolve the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Anu update?

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please improve the default icon. Please take a reference from [Here](https://prnt.sc/9tjJUcaJFx_c)

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul  Resolved

**Comment by Nikitajoshi39** [comment]
@akathuria289  issue fixed

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Still the same issue,

**Pull request closed without merging**
