### PR TITLE
Exchange rate and currrencies lang.

### PR DESCRIPTION
**Pull request by suraj-webkul**
[Exchange rate and currrencies lang.](https://github.com/bagisto/bagisto/commit/9c2d4c0d2b0c4a2373aa8117c0f4a9d7b3451660)

### CODE REVIEW

**Review by jitendra-webkul — APPROVED** [review]

**Comment by jitendra-webkul** [comment]
Resolve conflicts

**Comment by jitendra-webkul** [comment]
Conflicts

**Comment by suraj-webkul** [comment]
Resolved

**Comment by suraj-webkul** [comment]
Conflicts resolved

**Pull request merged**
