### PR TITLE
Issue #9500 fixed.

### PR DESCRIPTION
**Pull request by suraj-webkul**
Issue #9500 fixed.

### CODE REVIEW

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul 

Issue is still  not fixed, Fix the issue again, price issue is still appearing. Check the video's for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/417a0930-39ae-4856-9dcd-2ff5ea2bc87c


https://github.com/bagisto/bagisto/assets/92721837/22ab2287-4c27-4eee-bfab-02a89fe69734

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul 
Still some issue is remaining. Please check the video.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/c126b885-abb0-43c7-bbea-d500de19eacb

**Comment by suraj-webkul** [comment]
@ashishkumar-webkul sir,
this is not an issue.

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul Explain why this is not an issue as I have checked and still the filter outline is not with the round scrollers.

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
