### PR TITLE
Completed enhancement for the admin to set the frontend in maintenance mode #4242

### PR DESCRIPTION
**Pull request by devansh-webkul**
**ENHANCEMENT:**
Link: https://github.com/bagisto/bagisto/issues/4242

**STEPS TO EXECUTE THIS PR:**

Step 1: Run `php artisan migrate`.

Step 2: Run `php artisan vendor:publish --all --force`.

Done!

### CODE REVIEW

**Comment by devansh-webkul** [comment]
@ghermans,

I have queries that I have not added to this PR.

- What happens if the user is using maintenance mode via the command line i.e. `php artisan down`. At that time desync happens because all channel status is `false`. But the maintenance mode is on.

- Should I override the `php artisan down` method and update all channel status to `true` when the command is calling.

**Comment by ghermans** [comment]
@devansh-webkul when php artisan down is being executed all channels should go down indeed, as it means that the maintenance would have impact on all channels instead only one

**Comment by devansh-webkul** [comment]
@ghermans,

We need to update the `channels` table on the artisan command.

**Comment by ghermans** [comment]
@devansh-webkul 

I just setup a fresh install of Bagisto and after running the following below the frontend and admin are still up.
```bash
demo@bagisto:~/httpdocs$ php artisan down
All channels are down.
Application is already down.
```

1123AKnipsel

**Pull request merged**
