### PR TITLE
Product deleted exceptions in case admin delete a product.

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
https://github.com/bagisto/bagisto/issues/6447

## Description
If customer is adding a product into cart or adding it into whitelist which is deleted by admin.
So a exception page coming with product fetched attribute.

## How To Test This?
Login as a customer and view a product.
Now delete product form admin and add product into whitelist by customer.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
There should be a flash message if the customer is trying to add the deleted product to the wishlist.

**Comment by papnoisanjeev** [comment]
> @papnoisanjeev There should be a flash message if the customer is trying to add the deleted product to the wishlist.

@Sanjaybhattwebkul  Added warning message here.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The flash message looks like an exception, please find the screenshot [Here](https://prnt.sc/TRBW_kdA_oTi)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The flash message should be meaningful

**Comment by papnoisanjeev** [comment]
> @papnoisanjeev The flash message should be meaningful

@Sanjaybhattwebkul  updated content here.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Still getting the invalid flash message,** when the customer is trying to **add to the cart** the deleted product.
Please find the screenshot [Here](https://prnt.sc/FU-hwbnywkTZ)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The flash **message** should also be **visible** if the user trying to add the product to the **cart** from the **home page.**
Please find the screenshot [Here](https://prnt.sc/6t5xhItQBUrD)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Pull request merged**
