### PR TITLE
fixed issue #8883

### PR DESCRIPTION
**Pull request by shivendra-webkul**
## Issue Reference
fixed issue #8883

### CODE REVIEW

**Comment by Amitk-webkul** [comment]
@shivendra-webkul it is working fine.[Here](https://prnt.sc/WuGelNVKa5aU)

**Comment by jitendra-webkul** [comment]
Conflicts

**Comment by ashishkumar-webkul** [comment]
Checked and the Hover effect in Intervals for Dark theme is working fine, please check the screenshot [here](https://prnt.sc/QvxgbWT6k7pI)

**Comment by Amitk-webkul** [comment]
@shivendra-webkul, this issue is already fixed in [this](https://github.com/bagisto/bagisto/pull/8905) PR. so now you can close this PR.

**Pull request closed without merging**
