### PR TITLE
issue #6779 fixed

### PR DESCRIPTION
**Pull request by shubh-mehrotra**
## Issue Reference
#6779

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@shubh-mehrotra 
Please **resolve** the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@shubh-mehrotra 
Please **resolve** the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@shubh-mehrotra 
**Still not fixed**, please find the **screenshot** [Here](https://prnt.sc/q-TB74hepHYY)

**Comment by Sanjaybhattwebkul** [comment]
@shubh-mehrotra 
This is **working fine**, Please find the screenshot [Here](https://prnt.sc/ly3XfsQ9gY0H)
**Thanks** for your **contribution**,

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
