### PR TITLE
fixed mobile view ui issue in booking product #6991

### LINKED ISSUE #6991: Mobile view UI issue in booking product creating and editing them. Same slots all days, slot details.
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we **create** or **edit** a **booking product**, there we can see the options of **Same Slots all days,** **inspecting** the details in **mobile view** we will be able to see the UI **issue** in the slots.

**THIS ISSUE IS APPEARING IN BELOW BOOKING TYPES**
**1.** Appointment Booking
**2.** Rental Booking
**3.** Table Booking

### Preconditions

**Create** a **new booking product** for a clear **observation** of the UI issue in **mobile view**.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Add Product -> Create a new booking product.
2. Inspect the details in mobile view.
3. **Select** the **booking type** - appointment
4. Select the **Same Slots all days** - **yes or no.**
5. In both the **selections** of slots we will be able to see the UI **issue**.

### Expected Result

The UI of the slot details and the icons which are used should be in proper position.

### Actual Result

Please follow the **Screenshots** for a better understanding of the **issue**.

### Screenshots

**Screenshots**
Same Slots all Days - NO

Same Slots all Days No

Same Slots All Days - YES
Same Slots all Days Yes

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by akhtarkhan1**
## Issue Reference
Issue Fixed #6991

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
https://github.com/bagisto/bagisto/pull/7143

**Comment by Nikitajoshi39** [comment]
@akhtarkhan1 
Not fixed the **cross icon** and input fields are not in **alignment**. Please find the screenshot [Here](https://prnt.sc/nYzbQNlAPx4N)

**Comment by Sanjaybhattwebkul** [comment]
@akhtarkhan1 
Please resolve the conflicts.

**Comment by Sanjaybhattwebkul** [comment]
Closing this pull request as no activity from the last 3 days

Feel free to open a new pull request once done.

**Pull request closed without merging**
