### PR TITLE
Transaction amount exceed issue fixed #6545

### LINKED ISSUE #6545: The admin should be able to create transactions only with the Grand Total amount of the order.
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on transections inside the sales tab.
**3.** Create two transactions for the same invoice.

**Expected result:** The admin should be able to create **transaction** only with the **Grand Total** amount of **the order**.

**Actual result:** The admin is able to create a transaction with an **invalid amount**. Please find the below screenshot 

**Please find the screen recording [Here](https://www.awesomescreenshot.com/video/9897985?key=96920457d00918ccb4ba0f49a574208e) for reproduce the issue**

one

two

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#6545

## Description
Admin should not be able to create a **Transaction** amount greater than **Grand Total** amount of the order.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The admin should **not be able** to create a **transaction** with **0** amount, please find the screenshot [Here](https://prnt.sc/D28v-3Pti0DW)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please **resolve** the **conflicts**

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Still not fixed.** the transaction amount can **not be a negative** value, please find the screenshot [Here](https://prnt.sc/gRHpOg01zPkl)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 
Fixed for -ve numbers.

**Review by Sanjaybhattwebkul — DISMISSED** [review]

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
This is working fine, please find the screenshot [Here](https://prnt.sc/MkjXj_T99mCa)

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
