### PR TITLE
Make proper round corners for notification dropdown

### PR DESCRIPTION
**Pull request by lex111**
## Description

Currently, despite the border-radius set for notification dropdown, we can see that its edges are sharp, although should be  rounded.

## How To Test This?

| Before   | After    |
| -------- | -------- |
| image | image |

## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@lex111 

**Not working,** Please compline the **CSS** file. 
use _**npm run prod**_  for compiling the file.

**Comment by lex111** [comment]
@Sanjaybhattwebkul done :heavy_check_mark:

**Comment by lex111** [comment]
Although this bug is not related with the current change, but I fixed it. Replaced multiple media queries with a single relative viewport unit.

**Comment by Sanjaybhattwebkul** [comment]
@lex111 
Please **resolve** the **conflicts**.

**Comment by lex111** [comment]
@Sanjaybhattwebkul done :heavy_check_mark:

**Comment by Sanjaybhattwebkul** [comment]
@lex111 
Now, this is **working fine**,  please find the **screenshot** [Here](https://prnt.sc/hjT4ilwxexEY)
And **thanks** for your **contribution**.

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
