### PR TITLE
Fixed #3866

### LINKED ISSUE #3866: Compare icon is not coming in mobile view as well as layout issue on compare page in mobile view(default theme)
# Bug report

### Title
Compare icon is not coming in mobile view as well as layout issue on compare page in mobile view(default theme)

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. step1: open front end in mobile view 

### Expected result:
compare icon should come in header and there should not layout issue

### Actual result
https://prnt.sc/ua95vl

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3866

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
Done https://prnt.sc/uano69

**Comment by bhanu-webkul** [comment]
Icon issue has been fixed but layout issue still pending

**Comment by bhanu-webkul** [comment]
Screenshot 2020-09-03 17:32:26

**Comment by bhanu-webkul** [comment]
Screenshot 2020-09-04 11:22:47

**Comment by bhanu-webkul** [comment]
Done

**Pull request merged**
