### PR TITLE
Fixed #8660 (Calender Icon Compatible with Multiple Browsers)

### LINKED ISSUE #8660: Compatible the admin panel calendar icon with multiple browsers.
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Compatible with the admin panel calendar icon with multiple browsers.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. See the stats calendar icon OR
3. Click on 'edit/create product' inside the catalog/products
4. See customer group price date & time
5. See the error

### Expected Result

It should be shown in the same places.

### Actual Result

It is showing last in the Firefox browser. [Here](https://prnt.sc/a_KzJn3bCThb)

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference
#8660 

## Description
Set the display Property in parent div of calender icon

## How To Test This?
Go to 'Admin panel'
See the stats calendar icon OR
Click on 'edit/create product' inside the catalog/products
See customer group price date & time

### CODE REVIEW

**Comment by JunaidJaved248** [comment]
> @JunaidJaved248 Getting a few issues.
> 
> 1. Special price date input field shrink. [Here](https://prnt.sc/sq0PjAXJFBc1)
> 2. Getting the same above issue on on create event page. [Here](https://prnt.sc/MF8RQZwfOJOH)
> 3. Date-only attribute input field size shrink. [Here](https://prnt.sc/f-_OjSeHW-0-)
> 4. On the date and time input field calendar icon goes out on the left. [Here](https://prnt.sc/4jQzBjvviKqW)

@Amitk-webkul Let me check

**Comment by JunaidJaved248** [comment]
> @JunaidJaved248 Getting a few issues.
> 
> 1. Special price date input field shrink. [Here](https://prnt.sc/sq0PjAXJFBc1)
> 2. Getting the same above issue on on create event page. [Here](https://prnt.sc/MF8RQZwfOJOH)
> 3. Date-only attribute input field size shrink. [Here](https://prnt.sc/f-_OjSeHW-0-)
> 4. On the date and time input field calendar icon goes out on the left. [Here](https://prnt.sc/4jQzBjvviKqW)

@Amitk-webkul All Four Pointed Issue Fixed. You can test it now
Thanks

**Comment by Amitk-webkul** [comment]
@JunaidJaved248 All the issues are fixed and now it is working fine.

**Comment by JunaidJaved248** [comment]
> @JunaidJaved248 All the issues are fixed and now it is working fine.

Great

**Review by devansh-webkul — APPROVED** [review]

**Review by amit-webkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
