### PR TITLE
Add edit catalog image issue resolved

### PR DESCRIPTION
**Pull request by akathuria289**
## Description
On Add edit Catalog( product, category ) images placeholder adding issue is fixed

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please resolve the **conflicts**

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Not working**, the admin is not able to upload the product's image after merging this PR

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Please re-check

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Still not fixed,** if we are uploading any image then there is a **404  error.** Please find the screenshot [Here](https://github.com/bagisto/bagisto/pull/6611)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Any update ?

**Comment by abhishekkathuria** [comment]
@Sanjaybhattwebkul Please re-upload the screenshot URL

**Comment by Sanjaybhattwebkul** [comment]
@abhishekkathuria 
**Not** working, **still getting 404 error,** please find the screenshot [Here](https://prnt.sc/7MNNwDJdowLt)

**Comment by Sanjaybhattwebkul** [comment]
@abhishekkathuria 
Any update?

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Resolved

**Comment by Sanjaybhattwebkul** [comment]
@abhishekkathuria 
Please **resolve** the **conflicts**

**Comment by Sanjaybhattwebkul** [comment]
@abhishekkathuria 
Please **resolve** the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@abhishekkathuria 
Any update?

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Resolved the conflict

**Comment by akathuria289** [comment]
Closing this PR as created new PR - https://github.com/bagisto/bagisto/pull/6649

**Pull request closed without merging**
