### PR TITLE
Fixed #8685

### LINKED ISSUE #8685: Zip Code/PostCode should only allowed integer in Billing Address while checkout Process
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

When inputting the billing address during the checkout process, the system should prevent users from entering non-numeric values on the screen. However, if a user accidentally enters text or strings, the system will accept it, but the backend validation will detect the error. This error is not displayed to the user but can be found in the API response.
It should restrict user (show error message for adding integer value only)

### Preconditions

Customer must be logged in.
Customer should add order in cart & Proceed checkout 
And New billing address while checkout

### Steps to reproduce

1. Visit the Shop store.
2. Select a product and add it to your shopping cart, then proceed to the checkout.
3. Enter a new billing address, and intentionally input a non-integer value in the Zip/Postal code field.
4. When a non-integer value is entered, the system will not allow you to proceed to the next step due to an error occurring in the API, which is evident in the network response.

### Expected Result

It should only integer value in zip/postcode field

### Actual Result

It should only integer value in zip/postcode field

### Screenshots

Its allowing user to add non-integer value in zip/postcode field

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference
#8685 

## Description
Fixed #8685  Integer Allowed only validation rule applied

## How To Test This?
1.Visit the Shop store.
2. Select a product and add it to your shopping cart, then proceed to the checkout.
3. Enter a new billing address, and intentionally input a non-integer value in the Zip/Postal code field.
4. It show message now for only integer value allowed

### CODE REVIEW

**Comment by Amitk-webkul** [comment]
@JunaidJaved248 It is working fine.

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Its Done now

**Comment by Amitk-webkul** [comment]
@JunaidJaved248, Please validate with the special symbols except the (-) Hyphen sign. [Here](https://prnt.sc/TaDYG_rFpK1D).

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Its Done Please check

**Comment by Amitk-webkul** [comment]
@JunaidJaved248, Fix the same for the customer address. [Here](https://prnt.sc/nhmkkDcjpc2l)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Its Also Done Check Please

**Comment by Amitk-webkul** [comment]
@JunaidJaved248 Now It is working fine on Address create/edit. [Here](https://prnt.sc/QnU-OHHaC3IF) But not working on the billing address. [Here](https://prnt.sc/zPq9aT_1gpRw)

**Comment by JunaidJaved248** [comment]
> @JunaidJaved248 Now It is working fine on Address create/edit. [Here](https://prnt.sc/QnU-OHHaC3IF) But not working on the billing address. [Here](https://prnt.sc/zPq9aT_1gpRw)

Check now @Amitk-webkul

**Comment by Amitk-webkul** [comment]
@JunaidJaved248 Now it is working fine. [Here](https://prnt.sc/Goe_AQvxCtKx)

**Comment by devansh-webkul** [comment]
We will do it internally as we have other plans to handle this.

**Pull request closed without merging**
