### PR TITLE
Add Page Button on CMS Style on Mobile View (Issue Fixed #6821)

### LINKED ISSUE #6821: The add page button should be slightly right side in the mobile view.
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin on mobile.
**2.** Click on pages inside the **CMS tab.**
**3.** Try to add a new page.

Device name: **iPhone SE**

**Expected result:** The **add page** button should be **slightly** **right** side in the **mobile view.**

**Actual result:** The **add page** and **export** buttons are overlapping in the mobile view. Please find the screenshot [Here](https://prnt.sc/O8JBhjtT6_Fq)

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference

#6821 
## Description

I made changes in style of admin for aligning the position of Add Page Button on Mobile View. Specially Tested on iPhone SE & also tested mobiles. Its working fine after making changes .
## How To Test This?

**Steps To Test--**

1. Log in as an admin on mobile.
2. Click on pages inside the CMS tab.
3. Try to add a new page.

Device name: **iPhone SE**
## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
**Not fixed,** Still getting  the **issue** on the **Galaxy fold** device, Please find the screenshot [Here](https://prnt.sc/sWxibB5LVh5G)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Okay Let me check

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Issue Fixed Also in **Galaxy Fold** Device. 
Please find Screenshot [Here](image)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Review it also Please Requested Changes Done

**Comment by JunaidJaved248** [comment]
Hi @Sanjaybhattwebkul @jitendra-webkul 
Thanks for approving my PR #6839,
Please check these one also, Waiting for feedback on it. Here Pending PRs #6827 & #6809 
Thanks!!

**Comment by JunaidJaved248** [comment]
Any update @Sanjaybhattwebkul

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Now, this is **working** fine, **Thanks** for your **contribution**.

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
