### PR TITLE
Now we can set street address lines

### PR DESCRIPTION
**Pull request by gitesh-webkul**
#7464

### CODE REVIEW

**Comment by Amitk-webkul** [comment]
@gitesh-webkul 
Give the space for the first two lines while the admin tries to add the customer's address. [Here](https://webkul.chatwhizz.com/share/screenshot/642d1cf92a666707c40ed854)

**Comment by Amitk-webkul** [comment]
@gitesh-webkul 
Now It is working fine. [Here](https://webkul.chatwhizz.com/share/screenshot/642d48d1f0168c07d9f03102)

**Review by devansh-webkul — APPROVED** [review]

**Comment by devansh-webkul** [comment]
What about shops?

**Comment by devansh-webkul** [comment]
@amit-webkul and @Sanjaybhattwebkul,

Please check the shop also.

**Review by jitendra-webkul — APPROVED** [review]

**Comment by devansh-webkul** [comment]
Alright thanks.

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
