### PR TITLE
Configurables with varying variant types - Enhancement

### PR DESCRIPTION
**Pull request by AnnikaWolff**
After my last Pull Request #1782 was merged (thanks for that), I changed two small edges in the code, to let Configurable Types have other variants than just simple. 
A new product type for Tickets, for instance, could then extend the Configurable Type, having or not having a property called `variantsType`: 

```
class Ticket extends Configurable
{

    /**
     * Which type shall the variants be of
     *
     * @var string product type key
     */
    protected $variantsType = 'virtual';
}
```

### CODE REVIEW

**Comment by bhanu-webkul** [comment]
Hi @AnnikaWolff  

Getting exception While creating configurable product -
Screenshot - 2019-11-27T133050 542

**Comment by AnnikaWolff** [comment]
Hi @bhanu-webkul 

Oops, yep, sorry... pushed too quickly :)
Works now.

**Comment by bhanu-webkul** [comment]
Hi @AnnikaWolff 

Thanks for you efforts, now we are not getting exception while creating product but not able to create variants of different types apart from simple in configurable product. 
So could you please review again and comment accordingly.

**Comment by AnnikaWolff** [comment]
Hi @bhanu-webkul,

this PR only gives the possibility to choose a different variant type than simple by creating own product type classes extending the configurable type. Actually, I just refactored the original Bagisto code a little bit.

But simple variants are the default type, that is chosen, if no differing variant type is given. An example of a new product type having other variants than simple products, is not included in this PR - but I can provide one, if you wish.

**Comment by jitendra-webkul** [comment]
@AnnikaWolff thanks

**Pull request merged**
