### PR TITLE
Added bulk category delete functionality

### PR DESCRIPTION
**Pull request by jaseelbavu**
**ENHANCEMENT:**

>Added option to delete multiple categories by selecting a mass category.
**Issue ID : #4082**

### CODE REVIEW

**Review by ghermans — CHANGES_REQUESTED** [review]
Before deleting categories also verify that there are no products inside these categories.

In case the category still contains products than the first action should be to display a confirmation notification that there are still products in the categories, in case the admin confirms than first mass delete the products before removing the categories.

**Comment by jaseelbavu** [comment]
> Before deleting categories also verify that there are no products inside these categories.
> 
> In case there are still products inside the category than the first action should be to display a confirmation notification that there are still products in the categories, in case the admin confirms than first mass delete the products before removing the categories.

Hi @ghermans 
I have added a commit for this. Please verify and let me know if i have to do any good practice.

**Comment by vaishaliwebkul** [comment]
@jaseelbavu 
check the below mention cases as well

- if we try to delete an individual category using 'delete' button, then ask for confirmation if products exist in the category.
- category A which has no product , B which has n numbers of products, do below action to generate bug
 >> select both category and delete (in this case popup will ask "product exist")
 >> unselect the B category, now delete ( it will again ask "product exist") which is wrong.

**Review by ghermans — CHANGES_REQUESTED** [review]
@jaseelbavu can you please fix the items that @vaishaliwebkul mentioned?

**Comment by jaseelbavu** [comment]
@ghermans @vaishaliwebkul 
I have added a commit to the requested changes. Please review and verify.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
