### PR TITLE
Fixed issue #9990

### PR DESCRIPTION
**Pull request by shivendra-webkul**
## Issue Reference
Fixed issue #9990

### CODE REVIEW

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue is partially fixed and still the background issue is not fixed. background must be dark.

Fixed Points Screenshot -> https://prnt.sc/4B4a9Zw8jxdj

Need to add Dark background -> https://prnt.sc/08pc0ip5NQyH

**Comment by shivendra-webkul** [comment]
@ashishkumar-webkul  Background are also fixed

**Comment by ashishkumar-webkul** [comment]
Warning messages -> https://prnt.sc/_mIC8G8iCClS

Issue not fixed and conflict in PR.

**Comment by shivendra-webkul** [comment]
Conflicts resolved and warning message fixed

**Pull request merged**
