### PR TITLE
Fixed 8862

### PR DESCRIPTION
**Pull request by sunarcrajneesh**
## Issue Reference
#8862 

## How To Test This?

- Go to 'Shop'
- Add a product to the cart and proceed to checkout.
- Fill in all the required fields and select the preferred shipping/payment method.
- Click on the "Place Order" button.
- Access the 'Admin Panel.'
- Open the order and generate a invoice.
- Refund it now.
- Check the mailbox of the customer and the admin.

## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh It is working fine. [Here](https://prnt.sc/38YTu8UvXBWf)

**Review by devansh-webkul — APPROVED** [review]

**Comment by sunarcrajneesh** [comment]
Could you please let us know when we can expect these changes to be merged?

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh, Can you please update the branch? As commits are too much behind.

**Comment by sunarcrajneesh** [comment]
@Amitk-webkul,
Sure, updated now.

**Review by amit-webkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
