### PR TITLE
Added configuration to enable/disable image search feature

### PR DESCRIPTION
**Pull request by jaseelbavu**
**ENHANCEMENT:**

>Added configuration to enable/disable image search feature.
**Issue ID #3938**

**Steps**
>Enable/disable image search feature will be available under :
Configure > General > Content > Settings.
Screenshot from 2020-10-10 19-55-17

**Points to note:**

> As of /resources/themes/velocity/* folder is in .gitignore, this change will not affect in velocity theme even i have added it in under packages/webkul/velocity resource. So please let me know if I need to do anything about this issue.

### CODE REVIEW

**Comment by shubhwebkul** [comment]
Hello @jaseelbavu 
We really appreciate your contribution.

you can make changes inside **packages/webkul/velocity/resource/*** files and execute command php artisan vendor:publish --force
that's how your files will be changed and reflected as well.

Note:- to avoid executing command again and again you can  make changes inside **/resources/themes/velocity/*** directly and after completion of your work you can copy paste files inside **velocity** package.

I hope this will help, let me know if you have any further query.

**Comment by vaishaliwebkul** [comment]
@jaseelbavu 
It's working fine for the velocity theme as well.
Just update the image_search_status feature by default to be "True".

**Comment by jaseelbavu** [comment]
> Hello @jaseelbavu
> We really appreciate your contribution.
> 
> you can make changes inside **packages/webkul/velocity/resource/*** files and execute command php artisan vendor:publish --force
> that's how your files will be changed and reflected as well.
> 
> Note:- to avoid executing command again and again you can make changes inside **/resources/themes/velocity/*** directly and after completion of your work you can copy paste files inside **velocity** package.
> 
> I hope this will help, let me know if you have any further query.

Hi @shubhwebkul 
Thanks for the info. I have already added it in **packages/webkul/velocity/resource** file too but i was just concerned about the **/resources/themes/velocity/** files. I didn't know about the vendor:publish command takes care of it. Now its clear :+1: . 
Thank you.

**Comment by jaseelbavu** [comment]
Hi @vaishaliwebkul 
I have updated the VelocityMetaDataSeeder for image_search default values. But the checks are failing here. Correct me if i'm doing it in the wrong way.
Thank you.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
