### PR TITLE
Issue #7400 fixed.

### PR DESCRIPTION
**Pull request by suraj-webkul**
Issue #7400 fixed.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@suraj-webkul 
Fix this for **all packages**. admin and velocity

**Comment by suraj-webkul** [comment]
Fix this for all packages. admin and velocity
Done. https://github.com/bagisto/bagisto/pull/7401#issuecomment-1495341384
@Sanjaybhattwebkul

**Comment by Sanjaybhattwebkul** [comment]
@suraj-webkul 
This is **working fine**. please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/642d14e8f0168c07d9ef8842)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by devansh-webkul — APPROVED** [review]

**Comment by devansh-webkul** [comment]
This wont be done.

**Pull request closed without merging**
