### PR TITLE
Spanish language

### PR DESCRIPTION
**Pull request by danispiri**
Added Spanish language for Bagisto.
Translations for the BookingProduct, Core, Customer, SocialLogin, Ui and Velocity modules. Also for Laravel, Countries and States.
The translations for the Admin and Shop modules have been updated.

### CODE REVIEW

**Comment by ghermans** [comment]
There seems to be a issue with your pull request, please verify https://github.com/bagisto/bagisto/pull/4711/checks?check_run_id=2053097250#step:8:2872

**Review by danispiri — COMMENTED** [review]
Added spanish translation for states

**Comment by devansh-webkul** [comment]
Hi @danispiri,

Please check the test case. As your test cases are failing.

**Review by devansh-webkul — APPROVED** [review]

**Comment by vaishaliwebkul** [comment]
@danispiri 
Please add seeder for channels https://github.com/bagisto/bagisto/blob/5a267a64eb11a4487a275804eef5a4561356a6ac/packages/Webkul/Core/src/Database/Seeders/ChannelTableSeeder.php#L145

**Review by devansh-webkul — CHANGES_REQUESTED** [review]
Hi @danispiri,

Please check the test case also. It's again failing.

**Comment by vaishaliwebkul** [comment]
@danispiri 
please resolve conflicts.

**Pull request merged**
