### PR TITLE
Review Issue Fixed #5694

### LINKED ISSUE #5694: star ratings and reviews  alligment should be in same line in blisss theme in mobile view
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. click on any product in bliss theme

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Issue Reference
Link: https://github.com/bagisto/bagisto/issues/5694

### CODE REVIEW

**Comment by singhgagan03** [comment]
isssue not fixed

**Comment by singhgagan03** [comment]
issue not fixed 

Screenshot from 2022-02-15 11-34-11

**Comment by devansh-webkul** [comment]
Checking.

**Comment by devansh-webkul** [comment]
I am not able to reproduce this.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
This is **working fine**. Please find the screenshot [Here](https://prnt.sc/26w9a7s)

**Pull request merged**
