### PR TITLE
#2804 solved

### PR DESCRIPTION
**Pull request by shivam-webkul**
#2804 fixed.

### CODE REVIEW

**Comment by rahulcs0082** [comment]
Hi @shivam-webkul 

Add translations for every langauges, only added for english.

**Comment by rahulcs0082** [comment]
Hi @shivam-webkul 

Since we are using many languages for our system, so if you add any translations then it needs to add for every language not just only for English. 

#2864  - We don't need to do this, please refer the comment on same.

Kindly check the code standard - https://prnt.sc/sgl4es

**Comment by shivam-webkul** [comment]
> Hi @shivam-webkul
> 
> Since we are using many languages for our system, so if you add any translations then it needs to add for every language not just only for English.
> 
> #2864 - We don't need to do this, please refer the comment on same.
> 
> Kindly check the code standard - https://prnt.sc/sgl4es

@rahulcs0082  i will change the code as per as previous code.

**Comment by rahulcs0082** [comment]
HI @shivam-webkul 

Kindly revert changes for #2864 because we don't need this.

**Comment by rahulcs0082** [comment]
Hi @shivam-webkul 

Kindly resolve conflicts.

**Pull request closed without merging**
