### PR TITLE
Issue #3894 fixed

### PR DESCRIPTION
**Pull request by vishal-webkul**
**BUGS:**

issue: #3894

### CODE REVIEW

**Comment by bhanu-webkul** [comment]
https://prnt.sc/uc19z4 - update cart button is missing

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
update cart btn issue fixed

**Comment by bhanu-webkul** [comment]
done

**Comment by vaishaliwebkul** [comment]
closing this as issue is already closed.

**Pull request closed without merging**
