### PR TITLE
Issue Fixed #7079

### LINKED ISSUE #7079: QTY check should be applied on the simple product which are added in Group Product.
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we add a **simple product** to the **group product**, there we are able to **save** any qty,  even if the **simple product** qty is **less**.

Example.

**Simple Product QTY - 1000**

In Group Product when we add the same simple product we are able to save **above 1000.**

### Preconditions

**1. Simple Product with specific qty should be created in the Admin End.**
**2. We should be able to add the simpler product to the group product.**

### Steps to reproduce

1. Go to Admin End -> Create a Simple Product with specific QTY.
2.  Create a group Product and add the simple product to the Group Product.
3.  Once the product is added , please add the qty in group product more then the simple product.
4.  Now save the product.

### Expected Result

In group product we should not be able to save the group product if the simple product qty is more then that of the actual qty.
QTY check should be applied in the group product. less then or equal to the simple product qty should be added in the group product.

### Actual Result

Please follow the screenshot for a better understanding of the issue.

Here we are able to save the group product with more qty of the simple product.

### Screenshots

**Screenshot**

QTy

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference

#7079 
## Description

Qty Validation Check implemented on group product Item checking.
## How To Test This?

Go to Admin End -> Create a Simple Product with specific QTY.
Create a group Product and add the simple product to the Group Product.
Once the product is added , please add the qty in group product more then the simple product.
Now save the product.
## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
**Not working**, please find the **screenshot** [Here](https://prnt.sc/q82wzYtVDxMZ)

**Comment by JunaidJaved248** [comment]
image
@Sanjaybhattwebkul Its Working
Product have 92 quantiy and on adding 93 its showing message

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul I just recompiled the Changes. Check now

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
**Still not fixed**, please find the screenshot [Here](https://prnt.sc/2HEWqIWbcFlU)

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
any update?

**Comment by Sanjaybhattwebkul** [comment]
Closing this pull request as no activity from the last 16 days.

Feel free to open a new pull request once done.

**Pull request closed without merging**
