### PR TITLE
Status filter ui fixed

### LINKED ISSUE #7208: There should be an arrow icon if the customer is trying to filter the orders by status.
### Is your feature request related to a problem? Please describe.

There is no option for minimizing the status dropdown if the customer is trying to filter the orders by order status.

### Describe the solution you'd like

There should be an arrow icon if the customer is trying to filter the orders by status.

### Describe alternatives you've considered

status-issue

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amit-webkul**
Status filter ui fixed
#7208

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
The arrow **icon** should be **slightly bold**

**Comment by amit-webkul** [comment]
It's fine. Please check the [Link](https://prnt.sc/LfgJcIAaqjVN)

**Comment by Sanjaybhattwebkul** [comment]
@amit-webkul 
The arrow icon is **not in the center** of the select box.

**Comment by Sanjaybhattwebkul** [comment]
@amit-webkul 
The **arrow icon** is added **successfully** for the status filter. please find the **screenshot** [Here](https://prnt.sc/ST7sC3Nrc8aZ)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
