### PR TITLE
Social login completed

### PR DESCRIPTION
**Pull request by jitendra-webkul**
**BUGS:**

Social login completed

### CODE REVIEW

**Comment by AnnikaWolff** [comment]
Hello @jitendra-webkul 

Since this PR is merged, all pipeline checks are failing because of this migration: 
`packages/Webkul/SocialLogin/src/Database/Migrations/2020_06_25_162340_change_email_password_columns_in_customers_table.php`

Please, either revert that merge or fix the migration. Thank you.

**Comment by AnnikaWolff** [comment]
Hello again @jitendra-webkul 

it might probably be a good idea to configure the repository as such, that merges are not possible as long as the pipeline checks fail.
What do you think?

**Comment by jitendra-webkul** [comment]
Hi @AnnikaWolff,

Fixed in #3385

**Comment by jitendra-webkul** [comment]
> Hello again @jitendra-webkul
> 
> it might probably be a good idea to configure the repository as such, that merges are not possible as long as the pipeline checks fail.
> What do you think?

Yes you are right, PR should not be merge if pipeline failed.

**Pull request merged**
