### PR TITLE
fixed issue #8868

### PR DESCRIPTION
**Pull request by shivendra-webkul**
## Issue Reference
fixed issue #8868

### CODE REVIEW

**Comment by Amitk-webkul** [comment]
@shivendra-webkul On the create address it is working fine. Fix the same for the address edit page. [Here](https://prnt.sc/vSRqc6CTgpf3)

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul Please resolve the conflicts which are appearing.

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Fixed for the address edit page please check.

**Comment by Amitk-webkul** [comment]
@shivendra-webkul, If the options are disabled. Getting an error in the console and not able to save the address from the edit page. [Here](https://prnt.sc/WzhuBLhSs1cj)

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 
As I have checked the PR and there it was found that still the POST Code validation is still appearing after the required field is removed from the Admin end settings.

Please check the screenshots.

Admin - https://prnt.sc/ZurxBvlP2Tb5
Customer - https://prnt.sc/UnnIwgYX1EVT

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 
Checked and found that the issue has been fixed please check the video and screenshot.

Admin Configurations  - https://prnt.sc/M7d_uxSjb0Cu

**Video**


https://github.com/bagisto/bagisto/assets/92721837/5768045a-713d-4092-a653-0c30c32c5a70

**Review by devansh-webkul — APPROVED** [review]

**Pull request merged**
