### PR TITLE
bug fix - after removing customer address in admin panel page does not reload

### PR DESCRIPTION
**Pull request by AmooAti**
## Issue Reference
Link: #5098 

## Description
Hi, I used no content response because in datagrid-plus in do action method in axios success response it will reload the page and will flash the message, but if we use redirect back or redirect to a route because there's two URL loading flash message will be destroyed in first redirect call.
I also removed the config from the route but I think I did it wrong, but for this solution, it's useless, maybe in the future, we need that.

## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by devansh-webkul** [comment]
Hi @AmooAti,

However, this will still reload the page and there are multiple tabs in customer, on reloading tab is not persist. It will again redirect to the first tab i.e. `Information`.

Just try to not reload the page when you get success response just refresh the table and show the message.

**Comment by devansh-webkul** [comment]
Hi @AmooAti,

Still the same issue, the tab is not persisted.

**Comment by AmooAti** [comment]
Hi @devansh-webkul 
sorry I forgot this pr cause I'm so busy on a Magento project sorry about that.
I tried few things two weeks ago but the main issue was with doAction method in datagrid vue component that method finally will reload the page so I think some changes must be done there.
But for now sorry I'm truly busy so I can remove this pr for now, maybe somebody has an idea about that.
once again sorry 🌸.

**Comment by devansh-webkul** [comment]
No worry, I will fix it. I am closing this PR.

**Pull request closed without merging**
