### PR TITLE
Bengali translation ✅

### PR DESCRIPTION
**Pull request by heysagnik**
## Documentation
- [x] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@heysagnik 
You can do more commits on the same PR.

**Comment by heysagnik** [comment]
> 

Okay

**Comment by heysagnik** [comment]
@Sanjaybhattwebkul @jitendra-webkul @vivek-webkul This PR is ready to be merged.

**Comment by Sanjaybhattwebkul** [comment]
@heysagnik 
Still some **translations** are **missing**. please find the **screenshot** [Here](https://prnt.sc/sA1LV4oo2qcS)

**Comment by heysagnik** [comment]
Check [it](https://github.com/bagisto/bagisto/blob/a9f1cc92f622483c6afc65b0aa1e8c6dc1779703/packages/Webkul/Shop/src/Resources/lang/ben/app.php#L367) is already translated.

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by devansh-webkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
