### PR TITLE
Fixed issue #6689

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#6689

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The UI is **not good,** we can **improve** it, please find the screenshot [Here](https://prnt.sc/u1i_kEsOTbkP)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 

**Still not good**, please **arrow** icon for the subcategories, please take a reference from [here](https://prnt.sc/ji1SHQH838wt)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Any update?

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Fixed above issue. Please recheck

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
