### PR TITLE
feature : add login as customer to admin customer grid

### PR DESCRIPTION
**Pull request by gh-darvishani**
## Issue Reference
[ #7139 ](https://github.com/bagisto/bagisto/issues/7139)

| Before | After |
| -------- | -------- |
| before | after

## Description
we can add a new link to the admin customer grid and after clicking on it we should be able to login as a customer.
this feature is essential because sometime admin needs to check customer panel 

## How To Test This?
1: login admin panel
2: go to manage customer 
3: in the customer grid you should be able to see a open lock icon
4: click on it and now you can login as customer

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please resolve the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
**Still** getting the **conflicts**.

**Comment by Nikitajoshi39** [comment]
@gh-darvishani
 Hi there,
Not able to reproduce this issue. Can you please elaborate on this issue?

**Comment by gh-darvishani** [comment]
@Nikitajoshi39  where you get error? or where you have problem ?
are you see the lock btn on the customer grid?

**Comment by Sanjaybhattwebkul** [comment]
Hi there
Can you please add the **screenshot** of the **before-fix** and **after-the-fix**, Like [this](https://github.com/bagisto/bagisto/pull/7081#issue-1435775710)?

**Comment by Sanjaybhattwebkul** [comment]
@gh-darvishani 
This is **working fine,** please find the **screenshot** [Here](https://prnt.sc/9xu9qjImpVgj)

**Thanks** for your **contribution**.

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
