### PR TITLE
Tax issue resolved

### LINKED ISSUE #7201: The applied tax-category should be selected if the admin is trying to edit any variant.
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

If tax is applied on the configurable product then that tax category should be selected for all variants on the edit page.

### Preconditions

**1.** A tax category should be created.
**2.** The created tax should be applied to the configurable product.

### Steps to reproduce

**1.** Go to the 'admin panel'
**2.** Create a tax category.
**3.** Apply the created tax for configurable products.
**4.** Try to edit any variant of that configurable product.
**5.** Try to view the applied tax category.
**6.** See the error

### Expected Result

The applied tax category should be visible for all the variants if the tax is applied for any configurable product.

### Actual Result

The applied tax category is not visible for all the variants if the tax is applied for any configurable product.

### Screenshots

ss

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by suraj-webkul**
#7201
> Get tax for child product products in the configurable product, if applied

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@suraj-webkul 
If the admin is **removing** the **tax** for any **particular** variant then the **tax** should be **removed** for that variant.

**Comment by Sanjaybhattwebkul** [comment]
@suraj-webkul 
**Not fixed,** if the admin is **removing** the **tax** from **any variant** then **still** the tax is **applying** while the customer is trying to **order** that product, please find the **screenshot** [Here](http://localhost/master/public/women-off-white-solid-faux-tailored-fur-jacket)

**Comment by Sanjaybhattwebkul** [comment]
@suraj-webkul 
Any update?

**Comment by suraj-webkul** [comment]
Vivek Sir assigned me b2b module as i am working on it.

**Comment by suraj-webkul** [comment]
@Sanjaybhattwebkul 
New PR created for the same. so closing this PR.: #7240

**Pull request closed without merging**
