### PR TITLE
Fixed issue

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#6366

### CODE REVIEW

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
This is **working fine**, please find the screenshot [Here](https://prnt.sc/gFNy8QWR5NW5)

**Review by jitendra-webkul — APPROVED** [review]

**Comment by jitendra-webkul** [comment]
Resolve conflicts

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 

Any update ??

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please resolve the **conflicts**.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Resolved

**Pull request merged**
