### PR TITLE
UI - Responsiveness Issue in category page (Velocity theme) Fixed

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference
#5223

## Description
I have Fix Filter Category UI - Responsiveness Issue in category page (Velocity theme) Fixed, I have Updated the velocity.css file.

## How To Test This?
You can just pull the latest code. It will be applied
## Documentation
My Pull Request just need to update velocity theme latest update, then changes will be applied on project.

No Need to change anything, just need to pull latest code from repo

### CODE REVIEW

**Comment by JunaidJaved248** [comment]
@aayushbhatt18 have you reviewed the PR?

**Comment by aayushbhatt18** [comment]
This issue is fixed and can be merged.

**Comment by devansh-webkul** [comment]
Yes, just explore and try it.

**Comment by devansh-webkul** [comment]
@JunaidJaved248,

I will provide you feedback by today evening.

**Comment by JunaidJaved248** [comment]
Okay thanks

**Comment by devansh-webkul** [comment]
Hi @JunaidJaved248,

It's still not compiled, let me help you,

## For Production
- Go to the `packages/Webkul/Velocity` path.
- Run `npm run prod`.
- If `node_modules` not installed then run this `npm install && npm run prod`.
- After compilation, publish your package and check all the changes on the frontend.

## For Development
- Go to the `packages/Webkul/Velocity` path.
- Run `npm run watch`.
- If `node_modules` not installed then run this `npm install && npm run watch`.
- No need to compile as hot reloading automatically does for you.
- Once you are done with your development, then run `npm run prod`. This will compile your assets.
- And then push to the github.

**Comment by devansh-webkul** [comment]
Hi @JunaidJaved248,

I tested the category section in desktop white background is appearing. I am sharing both actual and expected results. Please have a look,

## Actual Result

Screenshot

## Expected Result

Screenshot (1)

**Comment by devansh-webkul** [comment]
Hi @JunaidJaved248,

In mobile view when I click on the filter the sidebar is down and detached from the side and top. I am sharing with you the actual and expected results (that looks in master).

## Actual Result

Screenshot

## Expected Result

Screenshot (1)

**Comment by JunaidJaved248** [comment]
@devansh-webkul I just checked it from live demo of bagisto. It was already detached. It doesn't affect by my PR changes Its another issue.
image
Anyway, let me check it & will fix it

**Comment by devansh-webkul** [comment]
@JunaidJaved248,

Just try the category which doesn't have an image.

**Comment by devansh-webkul** [comment]
Alright, this is a different issue. I am approving this.

**Pull request merged**
