### PR TITLE
sanitized content middleware added

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Info
- Sanitizing blade file. However, this will come with the cost now developer/site owner needs to add its custom HTML and they won't be able to use the direct predefined templates which we have built.

### CODE REVIEW

**Comment by Amitk-webkul** [comment]
Still facing issues in the below input fields.

-Applied command in the order comment from the admin panel.
-In shipment Carrier Title and Tracking Number.
-In product description and short description, and meta input fields.
-In the category, in the description field apply and edit again it is not showing the description input field.https://prnt.sc/CaBPPbERJN3c
-Customer first & Last name need to be validated from the admin panel.
-Catalog and cart rule name and description
-In the Email template, events mail and content need to fix.
-In CMS Meta input fields needs to validate.
-Inventory source description.
-Channel description, homepage content, footer content, meta description, and keywords.
-Admin user name.
-Role name and description.
-Slider's name, content, and slider path.
-Tax Rate identifier and zip code.
-Tax Category Description.

**Comment by Amitk-webkul** [comment]
@devansh-webkul 

After applying the script it is not showing the description field in the category. https://prnt.sc/87jfo2dWMhKR
Default added homepage content is showing as text.
Validate the footer content in velocity with the script.

**Comment by devansh-webkul** [comment]
This PR needs some more work. Marking as a draft.

**Comment by devansh-webkul** [comment]
@Amitk-webkul,

Please check now.

**Comment by Amitk-webkul** [comment]
@devansh-webkul,

While adding the address from the admin panel and entering the script in all the input fields so it is showing an [exception.](https://prnt.sc/PycJOwa26hPK)

Also, not able to create custom HTML

**Pull request closed without merging**
