### PR TITLE
Date of birth issue fixed #5423

### LINKED ISSUE #5423: The user should not be able to edit the record while the input field is giving a warning.
**Steps To reproduce**--

**1.** log in as a user
**2.** Click on the customer tab.
**3.** Create/ edit a customer and enter the wrong date of birth of the customer.

**Actual result:**  The user is able to edit the record while the input field is giving a warning. Please find the screenshot Here.

**Expected result:** The user should not be able to edit the record while the input field is giving a warning. 

Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6427881?key=c49ed7c9a91b83d83f9b758ed659b344).

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Issue Reference
Link: https://github.com/bagisto/bagisto/issues/5423

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
The issue is fixed but there is no date icon and date select option.
Please find the screenshot [Here](https://www.awesomescreenshot.com/image/18571067?key=25913b7045b4a98e90e22063e040cc77).

**Comment by devansh-webkul** [comment]
Checking!

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul,
The mentioned issue has been fixed.

**Comment by Sanjaybhattwebkul** [comment]
> @Sanjaybhattwebkul, The mentioned issue has been fixed.

@devansh-webkul 
Still **not fixed**. Please find the screenshot [Her](https://www.awesomescreenshot.com/image/18572979?key=133ffa78d3a915d7061bbb3619c10d51).

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul,

The mentioned issue has been fixed.

**Comment by Sanjaybhattwebkul** [comment]
> @Sanjaybhattwebkul,
> 
> The mentioned issue has been fixed.

@devansh-webkul 
**Thanks**, Now this is **working fine**

**Pull request merged**
