### PR TITLE
Fix for issue #5075

### PR DESCRIPTION
**Pull request by codeinnovers**
## Issue Reference

fix for issue #5075
## Description

modified file packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php to add the number of records in the datagrid and modified packages/Webkul/Admin/src/Resources/lang/en/app.php line 1550 to add the translation
## How To Test This?

can be tested on data grids in the admin attached screenshots for the reference
https://nimb.ws/y6TrvD
https://nimb.ws/QBK3wU (filtered grid)

## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by devansh-webkul** [comment]
Hi @codeinnovers,

Any update on both PRs.

**Comment by codeinnovers** [comment]
> Hi @codeinnovers,
> 
> Any update on both PRs.

Hello @devansh-webkul 
I will be pushing new updates soon

**Comment by devansh-webkul** [comment]
I have closed one PR, are you hitting new one or working on this.

**Comment by devansh-webkul** [comment]
Hi, @codeinnovers,

Any update on this?

**Comment by codeinnovers** [comment]
> Hi, @codeinnovers,
> 
> Any update on this?

Hello @devansh-webkul 
raised new PR https://github.com/bagisto/bagisto/pull/5344

**Pull request closed without merging**
