### PR TITLE
attributes in category page and in search now are ordered

### PR DESCRIPTION
**Pull request by 0x76db**
## Description

When I created a few attributes and added their options with the correct sort order it doesn't get sorted correctly in the search page. Turns out it just needed to be sorted.
I kindly ask you to merge this because it is quite important, especially when we have filters that has to be sorted for example the age groups of clothing products.

## Documentation
- [ ] My pull request requires an update on the documentation repository.

## Branch Selection

- [ ] Target Branch: master

### CODE REVIEW

**Comment by amit-webkul** [comment]
Hello @0x76db ,

I've reviewed your pull request and appreciate your contribution to Bagisto.

I am unable to reproduce the issue you mentioned in the pull request. Could you please provide more details on how to reproduce the issue, including screenshots or videos if possible?

Thank you.

**Comment by 0x76db** [comment]
1. You have to create a filterable attribute.
2. Add a few option to the attribute with a specific sort_order from the admin area or using raw database
3. Create them in random order for example create the 3-5 age range after 6-11. So that the id of the attribute option is lower.
4. Go on the search page and see that the returned attribute's options are not sorted.

**Comment by amit-webkul** [comment]
Hello @0x76db,

Thank you for your information. 
As per your information, i have followed all the steps one by one and after that, i was unable to see the error. Also, I have recorded the video for the same for you reference. 

Please check and feel free to tell us if I skipped any steps as per your information.

[Reference Video](https://webkul.chatwhizz.com/share/view-recording/66d83a4260b8692d4c40cb84)

**Comment by 0x76db** [comment]
I'm sorry I forgot a step.
If you go now and in DB put the sort_order of 3-5 age as 0 and 6-11 to 1 the order should be flipped, which will not happen.

**Pull request closed without merging**
