### PR TITLE
Fixed issue #9660

### PR DESCRIPTION
**Pull request by shivendra-webkul**
## Issue Reference
Fixed issue #9660

### CODE REVIEW

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 
As I have checked and verified your PR and there in RTL view i can see that the locale text is not appearing properly as they are getting cutted. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/ac318c58-c77a-4b7b-a83b-069ccd3736af

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 
Need to improve the UI of the content in Currency as the scroller has been added in locale due to which size has reduced but the currency drawer is still the same length.

https://prnt.sc/tXhvCZ3Ay6IK

https://prnt.sc/zEU8RDsPFkmn

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and working fine. Please check the video for reference. I have checked the issue in both RTL and LTR view and it is working fine.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/45141636-bfc8-4c10-9330-74e0d3f0a346

**Review by jitendra-webkul — DISMISSED** [review]

**Comment by jitendra-webkul** [comment]
Fixed conflicts

**Pull request merged**
