### PR TITLE
Change load routes in Packages

### PR DESCRIPTION
**Pull request by milwad-dev**

### CODE REVIEW

**Comment by devansh-webkul** [comment]
Hi @milwad-dev,

Thanks for the contribution.

There are more packages in Bagisto like admin, velocity, and many more, please check that also.

So that consistency should be maintain in all the packages.

**Comment by milwad-dev** [comment]
Hi @devansh-webkul .
Yes, I want to add separate PR, but whatever you say

**Comment by milwad-dev** [comment]
@devansh-webkul 
Complete.

**Review by milwad-dev — COMMENTED** [review]
Check all

**Pull request merged**
