### PR TITLE
Issue #3572 Enhancement Done

### PR DESCRIPTION
**Pull request by vishal-webkul**
**BUGS:**

issue: #3572

### CODE REVIEW

**Comment by bhanu-webkul** [comment]
@vishal-webkul 
Please check  calculation - https://prnt.sc/tys4so

**Comment by vishalkushwaha94** [comment]
@bhanu-webkul 
calculation fixed

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
calculation fixed

**Comment by bhanu-webkul** [comment]
Not fixed yet -----https://prnt.sc/tyu55f

**Comment by bhanu-webkul** [comment]
not working properly in case special price exist. 

Screenshot (36)

**Comment by bhanu-webkul** [comment]
@vishal-webkul 
Please  correct this as well -https://prnt.sc/u0r9yt

**Comment by bhanu-webkul** [comment]
Its not working for configurable type products

**Comment by bhanu-webkul** [comment]
@vishal-webkul 

https://prnt.sc/ubfw3o

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
above comment resolved

**Comment by bhanu-webkul** [comment]
@vishal-webkul 
fix same for default theme

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
fixed for default theme

**Comment by bhanu-webkul** [comment]
@vishal-webkul 
plz correct this- https://prnt.sc/ubxmdu

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
fixed multiple regular price issue

**Comment by bhanu-webkul** [comment]
@vishal-webkul   above issue has  been fixed but please check for downloadable products - https://prnt.sc/ubzmyc

**Comment by bhanu-webkul** [comment]
getting exception if admin put 0 in qty under customer group pricing 

Screenshot 2020-09-05 18:25:30

**Comment by vaishaliwebkul** [comment]
@vishal-webkul 
please resolve conflicts

**Comment by ghermans** [comment]
@vishal-webkul is it possible to resolve the conflicts again so we can merge this ?

**Review by ghermans — CHANGES_REQUESTED** [review]
@vishal-webkul  is it possible to resolve the conflicts again so we can merge this ?

**Comment by vishal-webkul** [comment]
@ghermans  Conflicts Resolved

**Pull request closed without merging**
