### PR TITLE
Paypal Server Side Integration

### PR DESCRIPTION
**Pull request by devansh-webkul**
# Paypal Server Side Integration

Server-side Paypal integration completed.

### Steps to execute this PR:

Step 1: Run `composer update`.

Step 2: Run `php artisan config:cache`.

Step 3: Run `php artisan vendor:publish --all --force`.

Step 4: Go to `Configuration -> Sales -> Payment Method` in Admin Section and add the required configs i.e.,
**Client ID**: String provided by Paypal
**Client Secret**: String provided by Paypal
**Accepted Currencies**: Comma separated currency code for e.g. INR,USD

Done!

Some related issue: #4219

### CODE REVIEW

**Comment by rahulcs0082** [comment]
Hi @devansh-webkul 

Please change this one - https://prnt.sc/vm6m1k.

**Comment by devansh-webkul** [comment]
@rahulcs0082,

I guess you have an old commit, please check the latest commit. I have already handled from the configuration.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
checkout Paypal SDK could not verify the valid sandbox details https://prnt.sc/vo9mvp

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

This is because in Sandbox mode currency is linked to the country. So business account's country is 'India' that's why it will take only a single currency.

Just try with currency 'INR' only.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
update the default title of PayPal smart payment https://prnt.sc/voe1u1

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

- Done with a default title.
- Should we need validation for the admin portion. As this is a comma-separated text field. Already configuration request is very bulky this will add one more check.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
ok, then no need to add validation as already instruction is given for adding currency.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
