### PR TITLE
Feature:  Dark theme velocity.

### PR DESCRIPTION
**Pull request by papnoisanjeev**
Adding  dark theme support  for velocity.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanje
**Not Working**, and **Not** getting any **option** to **change** the **dark** mode.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

1. Please fetch all updates first form my repository.
2. Clear your browser history or try incognito mode.
3. Restart your server once and publish vendor after fetching all updates from respective branch.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The option is **present** **only** for the **guest user**, Dark mode option should be **present for all users.**

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The product's **information** is **not visible** on the  **wishlist** and the **compare** page, please find the **screenshot** [Here](https://prnt.sc/ovzhPl_KWIqK)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The **arrow icon** for the categories **dropdown** should be visible on the **home page**. please find the screenshot [Here](https://prnt.sc/XqY9WSRP3QPv)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The **text** is **not visible** on the **profile** section, please find the screenshot [Here](https://prnt.sc/KWCPIcfR8ach)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please check **all tabs** inside the user's **profile section,** the **text is not visible**.

**Comment by papnoisanjeev** [comment]
> @papnoisanjeev Please check **all tabs** inside the user's **profile section,** the **text is not visible**.

@Sanjaybhattwebkul 
Updated.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Stil not fixed**, the form **labels** are **not visible** if the user is trying **edit** the **profile**, please find the screenshot [Here](https://prnt.sc/gBGyEBqPVz3p)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The buttons are **not** with **good UI,** please improve the **buttons** in the **dark theme.**

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please **resolve** the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The filter labels are **not visible** if the customer is trying to **shop by category.** please find the screenshot [Here](https://prnt.sc/njQcCU1Ywgag)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please **improve** the **product's card** on the home page.
Please take a **reference** from [Here](https://prnt.sc/MXLm2UJMziem)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The category images **are not visible** on the **shop by category** section.Please find the screenshot [Here](https://prnt.sc/M3nviHxvN_uL)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please **resolve** the **conflicts**

**Pull request closed without merging**
