### PR TITLE
Issue Fixed [#7137]

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#7137

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The message is **invalid** if the user is trying to **add** product to the **cart** from **list** page, please find the **screenshot** [Here](https://prnt.sc/bpJFL6KFLfe0)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Translation already added with [PR](https://github.com/bagisto/bagisto/pull/7129).
For now you need to add both PR then translation will work.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
If the customer is trying to by the product **directly**, in that case this is **not working**, please find the **screenshot** [Here](https://prnt.sc/PwZcg00kjzkc)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Still **not fixed,** please find the **screenshot** [Here](https://prnt.sc/rrrqSU1AXAfp)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Test-cases getting failed again and again, please check [Here](https://github.com/bagisto/bagisto/actions/runs/3546348206/jobs/5957496931)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please add validation for pages from where we can add products to the cart.

**Comment by papnoisanjeev** [comment]
> @papnoisanjeev Please add validation for pages from where we can add products to the cart.

Added check for velocity cart please check.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Still getting the same issue

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Still not fixed**, if the customer is trying to add a cart to the product from the compare page.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The product is **getting added** to the **cart**, if **Visible Individually** is **disabled**, Please find the screenshot [Here](Visible Individually is disabled)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Getting **warning message** if the customer is trying to add the product to compare, please find the screenshot [Here](https://prnt.sc/0uyXqvY1KJbh).

There should be **404** if the **Visible Individually** is **disabled** for that product.

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Now, this issue is fixed,

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The Customers **should not** be able to **share** the product if **Visible Individually** is **disabled** for that product.
And the product should be **removed** from **compare** and **wishlist** if **Visible Individually** is disabled. 

Please find the **screenshot** [Here](https://prnt.sc/KXjxDJR82zPu)

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
