### PR TITLE
option to add video in advertisement and product gallery for default theme

### PR DESCRIPTION
**Pull request by rahulcs0082**
option to add video in advertisement and product gallery for default theme

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@rahulcs0082 

- add validation message for media size(when trying to upload 5MB video then successfully saved but the video is uploaded)

- add video upload ability to the advertisement images as well.

**Comment by vaishaliwebkul** [comment]
@rahulcs0082 
1. product images are not changing on mouser hover in velocity

2. not able to click on video added for velocity theme
https://www.loom.com/share/a3d3b08c11924cdebec9b7935fc8f945

**Comment by rahulcs0082** [comment]
HI @vaishaliwebkul 

Kindly check, both issue has been resolved.

**Comment by vaishaliwebkul** [comment]
@rahulcs0082 
video is not supported in responsive view https://prnt.sc/vmwyqw

**Comment by rahulcs0082** [comment]
HI @vaishaliwebkul 

Kindly check, all mentioned issue fixed.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
