### PR TITLE
There is no way to access Admin panel if there is only one admin and …

### PR DESCRIPTION
**Pull request by dominikh8**
…he try to modify the role of Administrator and allow limited access. #5209

## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by aayushbhatt18** [comment]
There is an issue here.
When you create a custom role with limited access it shows "role update error".
There is no way to edit that particular role.
https://prnt.sc/1vyjkbq

What we have to do is:
We have to create a scenario where:

1. At least one role should be there with all the admin access (which cannot be edited / deleted)
2. At least one admin should be there with that particular role.

Now, what happening is, I'm able to edit the role with all admin access.

**Comment by devansh-webkul** [comment]
Hi @domko17,

Are you working on this?

**Comment by domko17** [comment]
@devansh-webkul
 I finished changes and push to pull request :)

**Comment by devansh-webkul** [comment]
Hi @domko17,

I appreciate your work but there are several problems with this PR,

- This can be done in a single file and some other way.
- Code styling problems.
- Translations not used.
- Looping used however which is not needed.

**Comment by domko17** [comment]
Hi @devansh-webkul,
do I have to fix the code fix? related to this task

**Pull request closed without merging**
