### PR TITLE
cross sell product and related product fixed

### PR DESCRIPTION
**Pull request by vijay-webkul**
## Issue Reference
#7410
> Fix limit for related /cross-sell products in products view page

### CODE REVIEW

**Comment by Amitk-webkul** [comment]
@vijay-webkul 
In the related products, it is still showing only 4 products.[Here](https://tinyurl.com/2gfcc95t)

**Comment by vijay-webkul** [comment]
@Amitk-webkul,
please check the screenshot [here](https://prnt.sc/fytLheAPSbX6):

**Comment by Amitk-webkul** [comment]
@vijay-webkul 
now It is working fine.

**Comment by Sanjaybhattwebkul** [comment]
@vijay-webkul 
This is **working fine**. please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/64267f982a666707c4036a5c)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by devansh-webkul** [comment]
It should be done from the configuration not hardcoded one.

**Comment by vijay-webkul** [comment]
@Amitk-webkul 
I have changed in feature configuration, please check **screenshot**:-
image
| image

**Pull request closed without merging**
