### PR TITLE
Issue #6898

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference

#6898 
## Description

Added Record Pert Page option in mobile view
## How To Test This?

1. Go to Store Front -> Show By Category -> Select any category -> Inspect in mobile view.
2. Refresh the Page in mobile view.
## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Is there any Issue in this PR, Bcz Check Failed, Should i have to create new PR or this PR is acceptable?

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Please **improve** the **alignment** between filters, please find the **screenshot** [Here](https://prnt.sc/6-jpLixe-Br7)

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Please **resolve** the **conflicts**,

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Okay, it will be resolved with fixing alignment issues.

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Check now. Conflicts Resolved with Alignment Issue fixing

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Resolve **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
This is **working fine,** please find the **screenshot** [Here](https://prnt.sc/3jEG4siKYMbw),
**Thanks** for your **contribution**.

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
