### PR TITLE
Fixed ui issue of shopping cart view page at bliss theme

### PR DESCRIPTION
**Pull request by deepaksinghgusain227**
#5729 

**fixed issue ui issue when we are try to book only booking product in bliss theme in checkout page (mobile view )**

### CODE REVIEW

**Comment by ghermans** [comment]
Hi @deepaksinghgusain227 the tests are failing due to the changes, can you please verify?

**Comment by deepaksinghgusain227** [comment]
Hi @ghermans please check the issue and igore the test because i have done the changes at ui part not at functionality part.

**Comment by singhgagan03** [comment]
working fine

**Comment by ghermans** [comment]
@deepaksinghgusain227 can you please resolve the conflicts?

**Pull request closed without merging**
