### PR TITLE
Fixed issue #6771

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#6771

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Not fided**, getting **404**. while **clicking** n any product's **name**

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Please re-check as its working fine

**Comment by Sanjaybhattwebkul** [comment]
> @Sanjaybhattwebkul Please re-check as its working fine

@akathuria289 
**Not working**, please find the **screenshot** [Here](https://prnt.sc/LaOsb8lPK0gP)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Any update?

**Comment by Sanjaybhattwebkul** [comment]
Closing this pull request as no activity from the last 16 months.

Feel free to open a new pull request once done.

**Comment by Sanjaybhattwebkul** [comment]
Fixed by this PR: https://github.com/bagisto/bagisto/pull/7145

**Pull request closed without merging**
