### PR TITLE
Issue Fixed #6799 (Relevant Message Shown now when User is inactive)

### LINKED ISSUE #6799: The warning message should be meaningful if the inactive user is trying to place an order.
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in a customer. and add any **item** to the **cart**.
**2.** Process for checkout.
**3.** Goto admin panel and **inactive** the **same user.**
**4.** Again come to the **shop**.
**5.** Continue the **checkout** process.

**Expected result:** The warning **message** should be **meaningful** if the **inactive** user is trying to **place an order.**

**Actual result:** The warning **message** is not  **meaningful** if the **inactive** user is trying to **place an order.**. Please find the screenshot [Here](https://prnt.sc/Y-IWAO2Ia1G0)

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference

#6799 
## Description

I have made change in onepage blade file, change common error message to relevant message of specific actions. 
## How To Test This?

1. Log in a customer. and add any item to the cart.
2. Process for checkout.
3. Go to admin panel and inactive the same user.
4. Again come to the shop.
5. Continue the checkout process.

## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul @jitendra-webkul I just checked the commit. Its working. I have attached the Screenshot. Please checkout
image

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul have checked it again?

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul @jitendra-webkul Can you please update about this PR.?

**Comment by JunaidJaved248** [comment]
Any update @Sanjaybhattwebkul ?

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Now, This is **working fine**, please find the screenshot [Here](https://prnt.sc/p9skyDz15t6-).
**Thanks** for your **contribution**.

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
