### PR TITLE
[#10102] Update Tax.php

### PR DESCRIPTION
**Pull request by helgvor-stoll**
Sorry,

The fork was deleted accidentaly and the PR #10102 automatically closed. Could you please reconsider the PR. Kind Regards

## Documentation
- [ ] My pull request requires an update on the documentation repository.

## Branch Selection

- [ ] Target Branch: master

### CODE REVIEW

**Review by amit-webkul — APPROVED** [review]

**Comment by amit-webkul** [comment]
Heelo @helgvor-stoll,

Please update the pull request, by comparing it with the 2.2 branch.

**Comment by helgvor-stoll** [comment]
Hello @amit-webkul
I was not  sure wbut if I well understand, the reference branch is the 2.2. Is it true?
I will take it into account for future

**Comment by amit-webkul** [comment]
@helgvor-stoll ,

Kindly reset your branch to Bagisto version 2.2, apply your changes, and commit again. This will update your PR to align with the Bagisto 2.2 branch, preventing any modifications to the master branch.

**Comment by helgvor-stoll** [comment]
@amit-webkul It's done

**Comment by amit-webkul** [comment]
A new pull request has been created for this issue, so I am closing this one.

PR Link : https://github.com/bagisto/bagisto/pull/10108

**Pull request closed without merging**
