### PR TITLE
Slovenian language added

### PR DESCRIPTION
**Pull request by BlazOrazem**
## Description

Slovenian language added.

## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by devansh-webkul** [comment]
Hi @BlazOrazem,

For providing language support you need to provide for the Admin and Shop package.

**Comment by BlazOrazem** [comment]
Hey @devansh-webkul,
so also for this repo: https://github.com/bagisto/laravel ? Anywhere else? :)
Cheers!

**Comment by devansh-webkul** [comment]
> Hey @devansh-webkul, so also for this repo: https://github.com/bagisto/laravel ? Anywhere else? :) Cheers!

Not this one. Only `bagisto/bagisto`.

**Comment by devansh-webkul** [comment]
Feel free to raise a new PR when its done.

**Pull request closed without merging**
