### PR TITLE
improve sluggable logic

### PR DESCRIPTION
**Pull request by thyseus**
improve the sluggify javascript snipppet a little bit so that multiple dashes (----) gets translated into a single dash.

In german products its common to use titles like "Foo - Bar" which would translate into "foo---bar" without this patch. ("foo-bar" is desired)

### CODE REVIEW

**Comment by jitendra-webkul** [comment]
@thyseus 

Please resolve conflict

**Comment by thyseus** [comment]
made a mistake wile merging, please wait.... :)

**Comment by thyseus** [comment]
Fixed :)

**Comment by thyseus** [comment]
can not reopen this PR so i made a new one: https://github.com/bagisto/bagisto/pull/1826

**Pull request closed without merging**
