### PR TITLE
[Fixed: #6745]

### PR DESCRIPTION
**Pull request by vivek-webkul**
[Fixed: #6745]

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@vivek-webkul 
**Not fixed,** getting the **blank page** if the customer is adding some blade syntax, Please find the s creenshot [Here](https://prnt.sc/QKCynT1wEe79)

**Comment by Sanjaybhattwebkul** [comment]
@vivek-webkul 
The product's **image** should be **visible** in the customer's review. if **uploaded** by the **customer**. Please find the screenshot [Here](https://prnt.sc/G2dMTzdqAFVa)

**Comment by vivek-webkul** [comment]
@Sanjaybhattwebkul 

Bagisto: dev-master
I cross-checked with the customer's review images and it's working fine.
Admin End: https://prnt.sc/VmHTJCYR9E37 
Product Detail: https://prnt.sc/cjp7FIt4-PSi

**Comment by Sanjaybhattwebkul** [comment]
@vivek-webkul 
I have set my **APP_URL** properly. and now this is **working fine**, please find the screenshot [Here](https://prnt.sc/0sgwBpodv35-)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
