### PR TITLE
Fixed zoom event which is not working when changing mouse hover from video to image #4283

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4283#issuecomment-734189503

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
zoom is now working but when moving to video it's changed position as shown below.
Screenshot_159

**Comment by jitendra-webkul** [comment]
Resolve conflicts

**Comment by devansh-webkul** [comment]
Confliction resolved.

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

In mine, it was working fine.

**Pull request merged**
