### PR TITLE
Showing discount to variant of config products for which catalog rule applied only.

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#6406

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Not working** The actual price is not visible please find the screenshot [Here](https://prnt.sc/eYm7Y8_zJjyG)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

As discussed and checked update working as expected.
Please re-test it again with master branch or latest release.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Not working** properly,

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Now this is **working fine,** Please find the screenshot [Here](https://prnt.sc/f9JvjnsneqyC)

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
