### PR TITLE
Fixed order status should not be completed until invoice state is pending #3734

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3734

### CODE REVIEW

**Comment by bhanu-webkul** [comment]
done

**Comment by ghermans** [comment]
If the invoice state is pending the order status should be **pending_payment** https://github.com/bagisto/bagisto/blob/b31d122924196f0d067194259ce2555edee5cff4/packages/Webkul/Sales/src/Models/Order.php#L12

**Comment by bhanu-webkul** [comment]
@ghermans   if we are showing                     pending payment status for pending invoice, then we should show payment overdue status when invoice status is overdue

**Comment by ghermans** [comment]
@bhanu-webkul i already mentioned this in https://github.com/bagisto/bagisto/issues/3644

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
In case of invoice -> pending meanwhile shipment is done then order status changed to processing instead of pending payment.

**Comment by devansh-webkul** [comment]
As the same case is happening in this PR https://github.com/bagisto/bagisto/pull/3765. So making one PR for both issues will be better.

**Pull request closed without merging**
