### PR TITLE
Added social share package

### PR DESCRIPTION
**Pull request by cagartner**
PR to merge the social share package: https://github.com/bagistobrasil/bagisto-product-social-share 

As requested by @saurav-webkul .

This will add social share links on PDP: 

- Facebook 
- Twitter
- Pinterest
- Linkedin
- Email
- What's App

image
image

With regards,
Carlos Gartner

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
Hi @cagartner , Thanks for your contribution!

I wanted to know about the use of text used in **Share Message** field https://prnt.sc/tt9jan, Is this field used only when sharing via E-Mail?? or work for all social share app??

**Comment by cagartner** [comment]
@vaishaliwebkul 

This message work's with almost all the options, just Facebook don't have support for this, but the others will work.

With regards,
Carlos Gartner

**Comment by vaishaliwebkul** [comment]
@cagartner 
I am trying to share via email and receiving messages converted to a string having + in place of space, Kindly check
Screenshot_4

**Comment by cagartner** [comment]
@vaishaliwebkul 

Solved, can you update the module to 0.1.2 version and try again?

With regards,
Carlos Gartner

**Comment by vaishaliwebkul** [comment]
@cagartner 
I am testing with an updated master version of Bagisto, how do I get it resolved?

**Comment by cagartner** [comment]
@vaishaliwebkul 

Updated composer.json of the PR, you need to run the `composer require bagistobrasil/bagisto-product-social-share` in a bagisto instance or get my branch and test.

With regards,

**Comment by vaishaliwebkul** [comment]
@cagartner 
Thanks!

**Pull request merged**
