### PR TITLE
Fixing slug bug mentioned in issue #5200

### PR DESCRIPTION
**Pull request by AbdullahFaqeir**
- Added UniqueSlug rule.
- Update validation rules for both categories and cms pages.
- Update slugify and slugify-target to validate generated slugs and update the slug to avoid conflicts.
- Fixed bug where edit page url_key isn't using slugify like create page.
- Fixed typoes in some comments.
- Code refactor.

## Issue Reference
#5200

## Description
When creating a category with (slug/url_key) categories, it causes the shop to display a json response as Velocity theme is using categories uri to return categories list to it's frontend.

## How To Test This?
- Create a category named Categories (which in turn will automatically generate a slug with `categories`)
- Visit the shop page.
- Click on the category named Categories.

## Documentation
- Added a new rule UniqueSlug.
- When creating editing (Category/ CMS Page) validate (slug,url_key) with UniqueSlug rule.
- Refactor validation rules for both (Category/CMS Page).
- Updated Vue Handlers (slugify & slugify-target) to validate auto-generated slugs to be unique, when the slug is unique, it returns the same slug with an incremental suffix Ex : categories-1, categories-2...etc.
- Fixed a bug in `page/edit.blade.php` not using slugify in url_key field.
- Fixed typos in some comments.
- Code refactor.
- Slug checks also includes checking routes defined with the same slug-like uri.

### CODE REVIEW

**Comment by AbdullahFaqeir** [comment]
Hi @devansh-webkul!

Can you please check this.

**Comment by ghermans** [comment]
@AbdullahFaqeir your PR will be review tomorrow

**Comment by devansh-webkul** [comment]
Hi @AbdullahFaqeir and @ghermans,

Due to the weekend, I am not able to provide feedback. Sorry for the delay, you will get feedback on this by today's evening.

**Comment by devansh-webkul** [comment]
Compilation files are missing that the reason may be.

**Comment by devansh-webkul** [comment]
Hi @AbdullahFaqeir,

Any update on this?

**Comment by devansh-webkul** [comment]
@AbdullahFaqeir,

I am taking a pull, will provide you feedback by today's evening.

**Comment by devansh-webkul** [comment]
@AbdullahFaqeir,

Compiled files are missing. Just run the `npm run prod` command in the UI package and commit the change.

I am not able to get the auto slug as mentioned in the info.

**Comment by AbdullahFaqeir** [comment]
@devansh-webkul Done bro

**Comment by devansh-webkul** [comment]
Hi @AbdullahFaqeir,

I am adding single categories slug, but it won't add, currently, i don't have any categories

Screenshot from 2021-10-14 12-07-17

**Comment by AbdullahFaqeir** [comment]
> Hi @AbdullahFaqeir,
> 
> 
> 
> I am adding single categories slug, but it won't add, currently, i don't have any categories
> 
> 
> 
> Screenshot from 2021-10-14 12-07-17
> 
> 

Along side checking the databases for occupied slugs, I also check against the routs (slug/uri) 😎.

**Comment by devansh-webkul** [comment]
But my point is, in the PR info it is mentioned that it will get an auto-incremented slug. So I am not getting auto-incremented slug.

**Comment by devansh-webkul** [comment]
Hi @AbdullahFaqeir,

Please check the mentioned file, this is `CMSPageController`, I can see this is handling by the same unique slug by passing the table name and column.

I just need to know is this handling the error messages also.

**Comment by devansh-webkul** [comment]
Hi @AbdullahFaqeir, any update on this?

**Comment by devansh-webkul** [comment]
Hi @AbdullahFaqeir,

If you want, I can take your commits and continue after this.

**Comment by devansh-webkul** [comment]
Hi @AbdullahFaqeir,

PR getting commits behind, any info on this.

**Comment by devansh-webkul** [comment]
Due to not getting any response, I am closing this one.

**Pull request closed without merging**
