### PR TITLE
Issue #4558 fixed.

### PR DESCRIPTION
**Pull request by rahulshukla-webkul**
Issue #4558 fixed.

### CODE REVIEW

**Review by vaishaliwebkul — APPROVED** [review]

**Comment by musawirjon** [comment]
I have updated both files. It's not worked for. Do I have to npm install in Shop as well. As I have did installed node_module packages in Velocity pkg.

**Comment by vaishaliwebkul** [comment]
@musawirjon 
you don't need to run npm command, you just need to add these [changes](https://github.com/bagisto/bagisto/pull/4560).
Run the below command once changes made:
`composer dump-autoload`
`php artisan optimize`
`php artisan vendor:publish --force `

it's working at my end https://www.loom.com/share/f589bed1ca3b429b9b5846572affea51

**Comment by musawirjon** [comment]
Have you checked it for dropshipping products. I already did changes in both two files as mentioned. And done with clear cache config things. But not working on my end.

**Comment by vaishaliwebkul** [comment]
@musawirjon 
If you are getting issue with the dropshipping product then kindly raise the issue report here https://github.com/bagisto/laravel-aliexpress-dropship/issues

**Comment by musawirjon** [comment]
Sure will add a ticket on above repo.

**Pull request merged**
