### PR TITLE
Category checked by ID #4498

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4498

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul  still able to delete root category having ID 9 
https://prnt.sc/xajzhe
https://prnt.sc/xajw19

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

This is because either you are not having a fresh installation or you are changing id from the DB. The root category which is coming with the seeder is of id `1`.

If the `root` can be changed then there should be one more checkbox for mentioning that it is a root category or something.

Otherwise, the one which is coming with the seeder can't be deleted.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul currently only the category having ID 1 is not deleted, if we assigned another category as root under channels then able to delete that category.

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

The mentioned issue has been fixed.

**Comment by vaishaliwebkul** [comment]
root category is getting deleted from mass delete action https://prnt.sc/xf95lv

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

The mentioned issue has been fixed.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
