### PR TITLE
Alert box issue during filtering #6640

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#6640

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
It is showing **two different-different** alert boxes for the same warning when the **customer** is trying to **filter the orders**. please find the screenshot [Here](https://prnt.sc/haboL4GOiQX-)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Removed  one alert box here.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Still **not working**. please find the screenshot [Here](https://prnt.sc/xHF2cu6Qlbdq),
The alert box should not be shown if all the required fields are filled

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by devansh-webkul** [comment]
Resolve conflicts.

**Comment by papnoisanjeev** [comment]
@devansh-webkul 

Conflicts resolved.

**Review by devansh-webkul — APPROVED** [review]

**Pull request merged**
