### PR TITLE
Fixed issue in which selecting variant with no image not doing anything #4708

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Bug
Link: https://github.com/bagisto/bagisto/issues/4708

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
parent images are getting duplicate when we select variant with no image in default theme

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

Not able to reproduce that,
https://prnt.sc/10gocvo

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

Mentioned changes have been done removed unnecessary parent images.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 

getting exception on wishlist when add configurable item https://prnt.sc/10i1hxr

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

That's not related to this PR, please raise a different issue for that.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
Yes, the issue is not related to this PR, so I have raised another error which is also related to the wishlist https://github.com/bagisto/bagisto/issues/4722.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
