### PR TITLE
Fixed category slug which is not translation based #4698

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Bug
Link: #4698

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
slug is not accepting the value in ar locale and also need to fix the validation https://prnt.sc/10djgf9

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

Mentioned changes have been done.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
getting 404 page when view category slug is in  ar locale https://prnt.sc/10iwykd

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Not able to reproduce that.

Screenshot from 2021-03-12 11-39-23

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
