### PR TITLE
#3026 fixed

### LINKED ISSUE #3026: Date validation error when editing Booking Products
# Bug report

### Title
I am not able to save any edited Booking Product due to validation errors for fields "Available From" and "Available To".

### Issue Description
When editing any kind of Booking Product, the date picker does not insert a correct date format - there is a 0 missing.
image
But even entering the missing 0 manually, the validation error does not disappear.
image
That is why I am not able to save the product.

### Preconditions
framework Version: v1.1.2
Latest Commit: [071fc16](https://github.com/Haendlerbund/bagisto/pull/23/commits/071fc16e138732d1768d2e7efafda49be83ee3a6)

### Steps to reproduce

    1. Create a new Booking Product
    2. Choose a date in fields "Available From" and "Available To"
    3. Insert missing 0 manually
    4. Try to save the product

### Expected result
The date picker should insert a date in the correct format. Any error messages should disappear as soon as the validation succeeds.

### Actual result

The date picker inserts a date with seconds of only one digit. Error messages do not disappear, no matter if the date format is correct and every validation condition is fulfilled.

### Please notice: I will provide a solution immediately.

### PR DESCRIPTION
**Pull request by AnnikaWolff**
Closes #3026

- I entered a missing configuration parameter in the vue-flatpickr component
- There is a known bug in vee-validate concerning the date_format validation rule. Because vee-validate version 2 is no longer supported, I followed the developer's suggestion [in this comment](https://github.com/logaretm/vee-validate/issues/2524#issuecomment-568306359) and implemented a custom date_format validation rule as workaround.

### CODE REVIEW

**Comment by rahulcs0082** [comment]
Hi @AnnikaWolff 

**after_datetime** validation not working properly. 
Kindly check - https://prnt.sc/seilat

**Comment by AnnikaWolff** [comment]
Hello @rahulcs0082 

you are right, thanks for telling me. 
After I have tried a lot to catch the value of the "Available From" field, I sadly gave up - I am not able to compare the two dates.

I have now removed my "after_datetime" function and left that part of validation as it was before. We should consider to update vue.js and vee-validate at this point. 
But for now, the bugfix of the pure date validation should be sufficient.

**Comment by rahulcs0082** [comment]
Hi @AnnikaWolff 

After validation is also not working - https://prnt.sc/sg11tg

**Comment by AnnikaWolff** [comment]
Hello @rahulcs0082 

after trying around a lot, I realised, that all my changes are completely unnecessary. 

In our shop, we really had that error, but a simple `php artisan vendor:publish --all --force` made it work. We never have used the `--force` flag before :confounded: 

So I reset all my changes. The flag `time_24hr` added to the flatpickr helped us, though. It is the only change I would like you to merge now. 

Thanks a lot!

**Pull request merged**
