### PR TITLE
Fixed issue #6386

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#6386

## Description
Fixed CSS

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
This is **working fine,** please find the screenshot [Here](https://prnt.sc/NTzZLG75EbTL)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by devansh-webkul — DISMISSED** [review]

**Comment by devansh-webkul** [comment]
Resolve conflicts

**Comment by jitendra-webkul** [comment]
resolve conflicts

**Comment by akathuria289** [comment]
@devansh-webkul  Sir @jitendra-webkul  Sir Resolved the conflict

**Comment by devansh-webkul** [comment]
Hi @akathuria289,

Just do one recompile and push again.

**Comment by akathuria289** [comment]
Done

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
