### PR TITLE
Upgrade all datagrids to datagrid plus

### PR DESCRIPTION
**Pull request by 4bdullatif**
## Issue Reference

#5292

## Description
As discussed today, there were some data grids are missing the "ProvideDataGridPlus" trait so I added the trait to the abstract "DataGrid" class, and refactored the remaining views with the datagrid-plus component.

### CODE REVIEW

**Comment by devansh-webkul** [comment]
Hi @4bdullatif,

There are some index pages test cases that are failing. Please check.

**Comment by devansh-webkul** [comment]
Hi @4bdullatif,

Any update on this?

**Comment by 4bdullatif** [comment]
Hi @devansh-webkul, sorry for being late ..
I am currently refactoring the tests, so maybe tomorrow I'll be done.

**Comment by devansh-webkul** [comment]
Hi @4bdullatif,

Are you working on this?

**Comment by devansh-webkul** [comment]
If you are facing an issue then let me know. I will help you.

**Comment by 4bdullatif** [comment]
Hi @devansh-webkul,

sorry for being late, actually I was facing an issue refactoring the tests.
The table is being rendered after the page fully loaded therefore the tests will always fail, I tried to use "wait" function but it requires the driver to be  a web driver, please [check](https://codeception.com/docs/03-AcceptanceTests#Wait)

I followed [the test in ](https://github.com/bagisto/bagisto/blob/master/tests/functional/Admin/Sales/OrderCest.php), and i discovered that you deleted the assertions.

**Comment by devansh-webkul** [comment]
Yes, actually you cannot test both JS and PHP if both are not seperated. This is the main reason test cases are failing. Many developers get confused because PHP is mostly mixed with JS.

No matter how much you add wait or anything but it will not pass the test because the table code and data will not rendered in the source file. If you check the cest log you will not find the element.

Now lets comes to the order table in which i removed the assertion. That test is only for testing the index page so i just removed the assertion.

Right now you can remove that assertion. And make it sames as orders table.

**Comment by devansh-webkul** [comment]
It will also not work but you can give a try.

**Comment by devansh-webkul** [comment]
@4bdullatif,

Instead of removing you can check this also,
https://github.com/bagisto/bagisto/blob/9b7727397d1e7e6dccca39dddc60ec9963bbeaac/tests/functional/Checkout/Order/OrderCest.php#L51

Because all datagrid plus is sending a ajax request in this way you can check the id assertions also.

**Comment by devansh-webkul** [comment]
Hi @4bdullatif,

Any update on this?

**Comment by ghermans** [comment]
Closing this PR due to no response.

**Pull request closed without merging**
