### PR TITLE
Issue Fixed #7158

### LINKED ISSUE #7158: Improve the product card on the home page.
### Is your feature request related to a problem? Please describe.

Improve the product card on the home page. if there is any bundle product then the size of product cards is not alignments.

### Describe the solution you'd like

**1.** Replace display: flex; with display: grid;  in the product card.
_**Use this CSS**_ :
  ````
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(225px, auto));
  gap: 20px;
  }
````
**2.** Remove the extra space between product detail in the product's card. **[** _for this take reference from the below screenshot_ **]**
**3.** The product card should be responsive on mobile.

### Describe alternatives you've considered

Please take a reference from the below screenshot.

image (2)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by prabhatkumaroc082**
issue #7158

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
**Not fixed,** still getting the UI issue if the **special price** is applied for any **product**, please find the below **screenshot**

ssone

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Any update?

**Comment by prabhatkumaroc082** [comment]
@Sanjaybhattwebkul review now.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Please **Improve** for the **special price**, please take a **reference** from the below screenshot.
image

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Any update?

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 

**Still not as expected**, please find the **screenshot** [Here](https://prnt.sc/p6XtS52oqXI5)

**_Please find the expected result below._**

image

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Any update?

**Comment by Sanjaybhattwebkul** [comment]
Closing this pull request as no activity from the last 2 months.

Feel free to open a new pull request once done.

**Pull request closed without merging**
