### PR TITLE
Refund issue #7170

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#7170

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
This is **working fine,** please find the screenshot [Here](https://prnt.sc/mldgh9awlvMo)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — DISMISSED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The **Inventory** of **bundle** products is **not updating** after creating the refund.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Please check

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Still not working**. the quantity of the product is not increasing after creating refund

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul it`s working fine https://webkul.chatwhizz.com/share/view-recording/63e0969daac9534fac237f4a

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Not working.** Please create **multiple inventories** and again reproduce the issue.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Now check

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Not working**, in the case of bundle products the product inventory is not updating after creating a refund.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Not working**, getting multiple input boxes for quantity while creating **shipping**, please find the **screenshot** [Here](https://prnt.sc/JORypExVwV0Q)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The product quantity is not updating after creating a refund of bundle products.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul It`s working fine please check again

**Review by devansh-webkul — APPROVED** [review]

**Pull request merged**
