### PR TITLE
Optimized and refactored code

### PR DESCRIPTION
**Pull request by jitendra-webkul**

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Not working, the customer should not be able to login without Email Verification

**Comment by jitendra-webkul** [comment]
> @jitendra-webkul Not working, the customer should not be able to login without Email Verification

Mention the steps to reproduce

**Comment by Sanjaybhattwebkul** [comment]
**1.** Enable  **Email Verification**  from the admin panel
**2.** Go to the shop
**3.** Sign in as a new customer.
**4.** Try to log in **without**  Email Verification

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
The **flash message** is **not** showing when the customer is **adding** the product to the **wishlist**

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Getting **exception**, if the admin is trying to **create shipment** of any order, please find the screenshot [Here](https://prnt.sc/UCBFzzqFiznC)

**Comment by Sanjaybhattwebkul** [comment]
Steps to reproduce:
**1.** Create an order of multiple products with multiple quantities.
**2.** Go to the admin panel
**3.** Create an invoice for the created order.
**4.** Create shipment for only 1 quantity of product.

**Pull request merged**
