### PR TITLE
Fixed issue #5335

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#5335

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please **improve** the **design**,

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 

Please **take** a **reference** from [Here](https://prnt.sc/Q_WvlYADMLI9)

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul  Please check

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The **public/private** label should be added **only** for the product for which the customer is generating the link.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul  Fixed

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Still not fixed**, not getting the share **link** and the page is getting **refreshed**. when the user is trying to share the wishlist.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The **checkbox** should be **checked** if the product is **public**.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul  Please check

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 

**Still not fixed**. not able to share **all** products **at once.**

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul  Fixed

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Still not fixed,** the **check all** checkbox is **not working** properly.

**Review by Sanjaybhattwebkul — DISMISSED** [review]

**Comment by devansh-webkul** [comment]
Need to fix this. Discussion done with Abhishek.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Any update ?

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please **resolve** the **conflicts**.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul  Resolved

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 

**Still not fixed**, not able to close the share wishlist **model box.**, please find the screenshot [Here](https://prnt.sc/0LYIe-YdTIaI)

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Please re-check it`s working fine 
https://www.awesomescreenshot.com/video/11193121?key=f5e166401c042e31c81e8c7ede99eb1d

**Review by Sanjaybhattwebkul — DISMISSED** [review]

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Re-check

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Still** getting the **conflicts**.

**Comment by akathuria289** [comment]
Closing this PR already has PR https://github.com/bagisto/bagisto/pull/6784

**Pull request closed without merging**
