### PR TITLE
Fix notification icons for dark theme

### PR DESCRIPTION
**Pull request by shivendra-webkul**
## Issue Reference
Fix notification icons for dark theme

### CODE REVIEW

**Comment by ashishkumar-webkul** [comment]
checked and found that the issue is still not fixed.
Please check the screenshot for reference -> https://prnt.sc/nCKtNkqnXQ9r

**Comment by shivendra-webkul** [comment]
Dropdown icons are also fixed.

**Comment by ashishkumar-webkul** [comment]
Not Fixed 

Order Processing icon is still  having issue.
https://prnt.sc/_X7HwOPUlVYz

**Comment by shivendra-webkul** [comment]
@ashishkumar-webkul  Fixed

**Comment by ashishkumar-webkul** [comment]
Checked and Found that now the issue has been fixed and working fine.

**Pull request merged**
