### PR TITLE
Added drag and drop

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue
#6716 

## Description
Added drag and drop

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please **link** the **issue** for which this PR is created.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Not working,** the rows are **not updating** after drag-drop.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul  Updating is not possible. Only Drag and Droping of row

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Please** resolve the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Any update??

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by cod3rshotout** [comment]
@Sanjaybhattwebkul @akathuria289 how to use this feature? could you add some documentation?

**Pull request closed without merging**
