### PR TITLE
Fixed issue #6743

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#6743

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please **resolve** the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please **resolve** the **conflicts**.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Fixed

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Still** getting the **conflicts**.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Resolved conflicts

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The **sub-categories** are **not visible** if the admin is creating any sub-categories **after adding a new locale.**

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Resolved

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Not  fixed**, still getting the **blank dropdown**, please find the **screenshot** [Here](https://prnt.sc/vMpnUYoZpEy5)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Now, this is **working fine**. please find the screenshot [Here](https://prnt.sc/XgDLkNkBXrR_)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by devansh-webkul — APPROVED** [review]

**Comment by jitendra-webkul** [comment]
Resolve conflicts

**Pull request merged**
