### PR TITLE
update npm assets

### PR DESCRIPTION
**Pull request by baijii**
- Before, I was unable to install or rebuild the assets of Ui, Shop and Admin, not with node 12 nor node 8
- I updated all js dependencies in Ui, Shop and Admin
- I excluded inline require statements in as imports to later use them in own webpack.mix.js to e.g. exclude vendors.
- introduced sourceMaps for dev

### CODE REVIEW

**Comment by rahulshukla-webkul** [comment]
Hi @baijii 

Kindly resolve conflicts.

**Comment by baijii** [comment]
Hi there, I resolved the conflicts. It should be ready to merge now. Thx.

**Comment by baijii** [comment]
Resolved conflicts again, still works.

**Comment by baijii** [comment]
Waiting for https://github.com/bagisto/bagisto/pull/1843 to be merged, for this pull request depends on it.

**Comment by phillipcodes** [comment]
+1 would love to use updated npm assets

**Comment by SteffenMahler** [comment]
Wow. Awesome work.

**Pull request merged**
