### PR TITLE
"Pending Payment" notification issue on admin panel  #6686

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#6686

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please use proper **translation** for order **status**, please find the screenshot [Here](https://prnt.sc/-d2a_lVCiaLC)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul
Please check it now.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
In **orders** page the issue is **still remain**, please find screenshot [Here](https://prnt.sc/5goE-Ryid0E0)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Now, this is **working fine**,  please find the screenshot [Here](https://prnt.sc/LqIC0RNUv5tg)

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
