### PR TITLE
Enhancement: Showing Offer price discount percentage #6367

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#6367

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Not working** properly, please find the screenshot [Here](https://prnt.sc/LMVzx11J07V9)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Please check now.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**Only** the **special** price is visible on the **cart page**, please find the below **screenshot**.
The **actual price** and the **percentage** of discount also **be visible** on the cart page.

one

two

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Resolve the conflicts.

**Comment by papnoisanjeev** [comment]
Due to multiple updates with function name and calculation with master branch this PR will no longer work as expected, so closing it.
Will create a new one for the same.

**Pull request closed without merging**
