### PR TITLE
Add fa locale to js validation

### PR DESCRIPTION
**Pull request by amirfrd**
## Description
this PR about to add FA (persian) locale to javascript validation with VeeValidator

### CODE REVIEW

**Comment by devansh-webkul** [comment]
Hi @amirfrd,

I am reviewing this, will let you know if any changes are required.

**Review by devansh-webkul — COMMENTED** [review]
Hi @amirfrd,

PR seems fine to me. :100:

- As I personally feel it should also have a default locales which comes with the Bagisto. It will be grateful if you add `fr`, `nl` and `tr` also. As `vee-validate` provide this. So only import is needed.

- With this change Bagisto is fullly synced its default lang with validation also.

## Additions

- [x] `fr` locale.
- [ ] `nl` locale.
- [x] `tr` locale.

**Comment by amirfrd** [comment]
Hi @devansh-webkul
I added all language bagisto support to js file

- [x] `fr` locale
- [x] `nl` locale
- [x] `tr` locale

**Comment by devansh-webkul** [comment]
Hi @amirfrd,

Thank you for your contribution. :rocket:

**Review by devansh-webkul — APPROVED** [review]

**Pull request merged**
