### PR TITLE
some refactor

### PR DESCRIPTION
**Pull request by moharami**
## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@moharami 
**Not working,** there is an **exception** if the admin is trying to update **Visible In Menu** of any **category**, please find the screenshot [Here](https://prnt.sc/DMjNVW5fE-JY)

**Comment by Sanjaybhattwebkul** [comment]
@moharami 
The page is getting **blank** if the customer is trying to **update** the **address**, please find the screenshot [Here](https://prnt.sc/R5C8cpaGb2YL)

**Review by jitendra-webkul — CHANGES_REQUESTED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@moharami 
Please **resolve** the **conflicts**

**Comment by jitendra-webkul** [comment]
No updates from last 23 days so i am closing this pr

**Pull request closed without merging**
