### PR TITLE
Fixed issue #9049

### PR DESCRIPTION
**Pull request by shivendra-webkul**
## Issue Reference
Fixed issue #9049

### CODE REVIEW

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 

Please check the PR again as there are some conflicts which are appearing.

**Comment by shivendra-webkul** [comment]
@ashishkumar-webkul Please check the PR conflicts resolved.

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 

checked and found that after merging the PR unable to see the admin page details and in console issues bhi aa rahe hai.

**Screenshots**

Screenshot from 2023-11-29 17-12-21

**Comment by shivendra-webkul** [comment]
@ashishkumar-webkul Fixed issue now it is working fine.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed, please find the screenshot [here](https://prnt.sc/C1roJVnRZW8e)

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
