### PR TITLE
change in guest compared list

### PR DESCRIPTION
**Pull request by jeetu-webkul**
## Issue Reference
Guest compare list
## Description
Guest compare list was managed from local storage, So changes in guest product compare list and now managing via database.

## How To Test This?
1. Click on the add to compared button then you can check the list of compared product and the number of compared product added in the guest its will show on that top of header

### CODE REVIEW

**Comment by mikeyapina** [comment]
Sorry, we initiate this request. I do not see the code to make the changes manually. I cannot do a build on this.

**Comment by mikeyapina** [comment]
That's great I am glad it is fixed but I need to manually change the code. I do not see the code anywhere.

**Comment by prateek-webkul** [comment]
> That's great I am glad it is fixed but I need to manually change the code. I do not see the code anywhere.

@mikeyapina ,

Yeah, we have added this PR to hold and checking it. But, if you want you may pull the code in your local. Here is the changed files https://github.com/bagisto/bagisto/pull/5798/files

Thanks

**Comment by mikeyapina** [comment]
packages/Webkul/Shop/src/Resources/assets/js/components/header-compare-with-badge.vue

there is no such file in the code base I have ...

**Pull request closed without merging**
