### PR TITLE
Tax Enhancement #4463

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Description
Link: #4463 

## For Developer
- In `AbstractType` class, `evaluatePrice` method is added. This method will check for tax inclusion and give the price based on the evaluation.
- And this method is only used in displaying portions i.e. `getProductPrices` and `getPriceHtml` method. So that `getFinalPrice` method remains untouched.
- `Tax` class enhanced.

## How To Test This?
- Configuration is given in the backend,

  Screenshot

- With inclusive taxes,

  Screenshot(1)

- Without inclusion,

  Screenshot(2)

## Documentation
- [x] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by ghermans** [comment]
@devansh-webkul testing with default tax settings works as it should, but still need to verify if it works when the customer is based in a different country

**Review by ghermans — COMMENTED** [review]
@devansh-webkul testing with default tax settings works as it should, but still need to verify if it works when the customer is based in a different country

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
 
- [ ]  Test the tax-inclusive enable functionality with login customer with saved address

**Bug:** Not getting price inclusive tax amount https://prnt.sc/12u7fsf

- [ ] spell error https://prnt.sc/12u7itl

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul and @ghermans,

I just checked the code in the backend and the address is fetching on the basis of the default address that's why it's taking the default country from the config again.

I think default address functionality is missing at the customer end. You can verify this by setting the default address from the admin end.

In the master branch, if you set the default country in the  `config/app.php` then the issue will again rise.

And for the typo, i am working on it.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
I have reported the issue https://github.com/bagisto/bagisto/issues/4875 so will continue this PR once this fixed

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul  and @ghermans,

The latest master version is merged in this PR, now it is ready for testing again.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
For the configurable type of product, the price inclusive tax doesn't show want select variant, please check https://prnt.sc/1345k1t

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Mentioned changes have been done.

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul and @ghermans,

- I just checked for the grouped product cases and in the master version tax is not applied on the parent basis, if the child has a tax then it will show tax otherwise tax not applied.
- So keeping this in mind, i just hanlded in this PR also. So that master and this PR should be in sync.

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Mentioned changes have been done.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
