### PR TITLE
Carousel Width Updated #6276

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Issue Reference
Link: https://github.com/bagisto/bagisto/issues/6276

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
There should not be any **extra space** between the **products**. Please find the screenshot [Here](https://prnt.sc/-KAe5r2UpDL5).

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
The product images are still **not showing properly** when the user is trying to **slide** the products in mobile view. Please find the screen recording [here](https://www.awesomescreenshot.com/video/8743877?key=fe0178873435059450434c8612fe2bb5).

**Comment by devansh-webkul** [comment]
The mentioned issue has been fixed.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
The products should be **slide** If the user is trying to slide products, **without using** the **Carousel** icons.  in mobile view

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Pull request merged**
