### PR TITLE
wish-list icon spacing issue on compare product's page #6793

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#6793

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please resolve the **conflicts**

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Recompiled,  please check.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please **resolve** the **conflicts**.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Recompiled, Please check.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Still showing **conflicts**.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Resolved please check.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 

**Not fixed**. the **cross icon** should be in **center** in the **Arabic** locale.Please find the screenshot [Here](https://prnt.sc/00WykbIBcqfw)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 

Please resolve the **conflicts**.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

done.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The size of the cross icon should be the same  for all locales

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The **delete all** button should be on the **top-left corner**. in **Arabic** locale. Please find the screenshot [Here](https://prnt.sc/Zlc7QjTeqKn9)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

All updates done here for Arabic locale please check.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Now this is **working fine,** please find the **screenshot** [Here](https://prnt.sc/P0b6-pZYoBVl)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
