### PR TITLE
Revert "Issue #6353 fixed."

### PR DESCRIPTION
**Pull request by jitendra-webkul**
## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul,

Please verify the changes.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul @jitendra-webkul 
This is **working fine**, please find the below screenshot.

Screenshot(1)
Screenshot

**Review by Sanjaybhattwebkul — DISMISSED** [review]

**Comment by Sanjaybhattwebkul** [comment]
The Rest UI issues are fixed [here](https://github.com/bagisto/bagisto/pull/7344). for the same.

**Comment by devansh-webkul** [comment]
Making new pr.

**Pull request closed without merging**
