### PR TITLE
Issue #5335

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#5335

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please **resolve** the **conflicts**.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Resolved conflict

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The customer is **not** able to **copy** the **sharing link**, please find the **screenshot** [Here](https://prnt.sc/Z50k5yPzi8NZ),
The page is **getting refreshed.**

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The product's images are also cropped if the Wishlist sharing is disabled for the customer.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Any update?

**Comment by Nikitajoshi39** [comment]
@akathuria289 
Not fixed, the page is getting refreshed while the customer is trying to generate the share link

**Comment by akathuria289** [comment]
@Nikitajoshi39  Fixed

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Still not fixed, please take a reference from [here](https://prnt.sc/9kCob2jev85d) and improve the functionality.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Fixed

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Removed the functionality

**Comment by devansh-webkul** [comment]
Create a new pull request when this is fully done.

**Pull request closed without merging**
