### PR TITLE
Fixed translation issue on uploading high size image #3570

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3570

### CODE REVIEW

**Comment by bhanu-webkul** [comment]
still same message

**Comment by bhanu-webkul** [comment]
Done

**Comment by devansh-webkul** [comment]
Issue: https://github.com/bagisto/bagisto/issues/3615
Fixed Favicon Image Issue.

**Comment by vaishaliwebkul** [comment]
working now for both favicon as well as logo image

**Pull request merged**
