### PR TITLE
Arabic And Persian Support Added To DOM PDF #4420

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Bugs
The Invoice PDF in Arabic is not able to render Arabic properly. The alphabets are getting isolated instead of staying connected.
Link: https://github.com/bagisto/bagisto/issues/4420

## Additions
- After lots of research `dompdf` support can only be fixed with this package. In the latest version of `ar-php`, they have given the support via composer and clean way as well.
- Added one optional param to the method i.e. `formatBasePrice`, which gives the ability to encode the formatted price.

## Steps to execute this pull request
- Run `composer install`.
- Done!

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
getting an exception when printing invoice 
Screenshot_209

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

You composer package not installed properly, please remove vendor folder and re-run the command `composer install`.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
I already followed all the steps mentioned above but still getting this error.

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Try `composer install --no-cache` and then `composer dump-autoload`.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
I have Reverified this PR with a fresh project and still getting the same error.

Environment configuration are mentioned below

- composer version 2.0.2

- PHP Version 7.4

**Review by ghermans — CHANGES_REQUESTED** [review]
@devansh-webkul I did a fresh install with your fork and couldn't reproduce the error that @vaishaliwebkul refers to.  

However i did notice that the currency isn't being displayed on the invoice.
testArKnipsel

**Comment by devansh-webkul** [comment]
@ghermans,
Fixed the currency symbol issue.

@vaishaliwebkul
I will try to reproduce that on the latest one also. I will update you regarding the same.

**Review by ghermans — APPROVED** [review]

**Comment by fahadkhan1740** [comment]
There is one more issue related to Arabic in Invoice. I am using Kuwaiti Dinar in the currency which should be `.د.ك` , but it is opposite instead as shown in the image below.

image

**Comment by devansh-webkul** [comment]
Hi, @fahadkhan1740,

You can raise your issue here, as this will help all the Arabic community as well,
https://github.com/khaled-alshamaa/ar-php

**Comment by khaled-alshamaa** [comment]
> There is one more issue related to Arabic in Invoice. I am using Kuwaiti Dinar in the currency which should be `.د.ك` , but it is opposite instead as shown in the image below.
> 
> image

Can you try the latest version now (i.e. using version 6.0.0 of ar-php library)? This should resolve your reported issue of د.ك.

**Pull request merged**
