### PR TITLE
wishlist text removed

### PR DESCRIPTION
**Pull request by rachana-webkul**
## Issue Reference
#7320
>wishlist text removed from card body

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@rachana-webkul 
**Not working,** the wishlist text should be removed only from the card body.

**Comment by Sanjaybhattwebkul** [comment]
@rachana-webkul 

**Not fixed**, the wishlist **text** should not be removed from **compare** page. Please find the **screenshot** [here](https://prnt.sc/uL2uxAdc-ICA)

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul 

Please raise issue first and explain what is need to do.

**Comment by Sanjaybhattwebkul** [comment]
@rachana-webkul 
**Add** a trash icon [here](https://webkul.chatwhizz.com/share/screenshot/63f4aebcbf991905516c080c), and remove the wishlist icon.

**Comment by Sanjaybhattwebkul** [comment]
@rachana-webkul 
Still, the wishlist icon is visible instead of the trash icon.

**Comment by rachana-webkul** [comment]
@Sanjaybhattwebkul 
wishlist text and trash icon issue fixed,please verify

**Comment by Sanjaybhattwebkul** [comment]
@rachana-webkul 
Now this is **working fine**.please find the **screenshot** [Here](https://prnt.sc/rsisCUb8AoNh)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by devansh-webkul — APPROVED** [review]

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
