### PR TITLE
Issue #6991 Fixed

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference

#6991 
## Description

UI Issue Fixed
## How To Test This?

Go to Admin -> Catalog -> Products -> Add Product -> Create a new booking product.
Inspect the details in mobile view.
Select the booking type - appointment
Select the Same Slots all days - yes or no.
In both the selections of slots we will be able to see the UI issue.
## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Please resolve the **conflicts**.

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Conflicts Resolved

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
**Not fixed,** getting **same** issue, please find the **screenshot** [here](https://prnt.sc/CtyN9BfTKYfb)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Check now Please

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
**Still not fixed**, please find the **screenshot** [Here](https://prnt.sc/fARtWHqZ9lP1)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Issue was related to date icon was not aligned. That Fixed now, But now in recent attached screenshot you are pointed cross icon, can you elaborate it?

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Yes, **you are right** but the **cross** icon is **not** in **alignment**, so we **need** to **fix** it, please take a **reference** from [here](https://prnt.sc/y0okL5HtBihp) for cross and date icon's **alignment**.

**Comment by Sanjaybhattwebkul** [comment]
Closing this pull request as no activity from the last 16 days.

Feel free to open a new pull request once done.

**Pull request closed without merging**
