### PR TITLE
Issue #3494 fixed

### PR DESCRIPTION
**Pull request by vishal-webkul**
**BUGS:**

Issue: #3494 
**For things other than bugs:**

> Describe that thing in very short line, word limit is 200.
> Otherwise use **issue #id** if the issue was filed as **feature** request.

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@vishal-webkul 
Images are not visible in compare list please check https://prnt.sc/tuy9os https://prnt.sc/tuy9vv

**Comment by vishal-webkul** [comment]
@vaishaliwebkul 
Image issue fix please let me know if any issue remain

**Comment by vaishaliwebkul** [comment]
not working ..

**Comment by vaishaliwebkul** [comment]
working fine

**Pull request closed without merging**
