### PR TITLE
Fixed Issue #6841

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
 #6841

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please resolve the **conflicts**

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please **resolve** the **conflicts**.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Done.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
**This is working** please find the **screenshot** [Here](https://prnt.sc/XZOgCa1kZF29)

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
