### PR TITLE
Fixed channel drop down which gets blank when admin panel filter based on new locale #4588

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4588

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 

- [ ] needs to update this at all place where channel dropdown exists in admin

https://prnt.sc/yye1rt
https://prnt.sc/yye9ak
https://prnt.sc/yyeew8

- [ ] In data grid instead of default channel, All channel options should be selected as recently we have added the locale filter based on channel in admin end.

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Mentioned changes have been completed.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
do the below update for the locale filter

- [ ] when you filter admin locale (add new locale and filter from top right corner)  and go to product grid https://prnt.sc/z239b3

- [ ] No filteration should be done in channel grid when admin filter new locale https://prnt.sc/z23l9a

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
kindly fix both issue.
https://prnt.sc/z2txf6
https://prnt.sc/z2ucqw

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Mentioned changes have been completed.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
category data is not coming for fallback locale in edit product page

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Mentioned changes have been done.

**Review by vaishaliwebkul — APPROVED** [review]

**Review by rahulshukla-webkul — APPROVED** [review]

**Pull request merged**
