### PR TITLE
issue in date blank fixed 

### PR DESCRIPTION
**Pull request by vijay-webkul**
## Issue Reference
#7419 

-> Issue in date after inserting data, the date was not empty showing fixed. find attached below.
[link](https://prnt.sc/S9__JIPhETAc)

### CODE REVIEW

**Comment by vijay-webkul** [comment]
@Amitk-webkul 
please check again resolved
[Link](https://prnt.sc/8saDk-YtYoxY)

**Comment by Amitk-webkul** [comment]
@vijay-webkul end date is fixed. But while I m saving without entering the date and saving and editing again while entering the date here it is showing the year in -1. It should be shown in the present year.[Here](https://tinyurl.com/2oa9jp56)

**Comment by Sanjaybhattwebkul** [comment]
@vijay-webkul 
Fix the same for the catalog rule as well.

**Comment by Amitk-webkul** [comment]
@vijay-webkul 
Getting **Duplicate commits.**
Please resolve the duplicate commits.

**Comment by vijay-webkul** [comment]
A new pull request is created for the same issue:#7448

**Pull request closed without merging**
