### PR TITLE
Fixed role-based security issue in which user with no permission has acces to some admin pages/controls #4399

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4399

Added ACL and arranged the ACL's array in similar order which is in nav.

### CODE REVIEW

**Comment by devansh-webkul** [comment]
After discussion with @vaishaliwebkul, mass delete and update needs to be updated for all package. So putting this in draft mode.

**Comment by devansh-webkul** [comment]
I just check `admin` routes and added ACL where I found `mass-delete` and `mass-update`. Still, if any area is missing then let me know.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
user with no permission can able to access the below mentioned routes

sales/orders/view/7
sales/invoices/view/4
sales/shipments/create/7
sales/shipments/view/1
sales/refunds/create/7
promotions/subscribers
tax-rates/create
tax-categories/create

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

I have done the first one which is checked, the second one is a type of enhancement because `mass-delete`, `mass-update`, `edit` and `delete` is present all over the admin interface.

If i do in Datagrid package this will impact the shop as well as custome solutions as well. Changes needs to be done on individual classes.

**Comment by devansh-webkul** [comment]
Trying with the parent one.

**Comment by devansh-webkul** [comment]
There are some data grids in which methods named are not synced with the routes method. So i just changes the method key in the some datagrid classes. I just prefer this one because previosuly post methods has been moved although vice versa can also be possible.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
Tested the ACL for all user permission, please check the below points that need to be fixed.

- [ ] Add order cancel permission also, by default user can cancel the order if order view permission is given.

- [ ] ACL for copy product, promotions.

- [ ] ACL for customer address, customer note https://prnt.sc/wnaroc

- [ ] remove currency-> mass delete option in user role permission https://prnt.sc/wnaugq as currency mass delete option does not exist in currency datagrid. https://prnt.sc/wnato5

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

Mentioned points has been fixed.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
