### PR TITLE
Default Variant Enhancement Completed #4911

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Description
Link: https://github.com/bagisto/bagisto/issues/4911

## For Developers
- One `additional` JSON column added in `product` table. So attributes that are not computational, we can place them there to avoid join queries.
- In the `Configurable` class in the namespace `Webkul\Product\Type`, provided some methods to get, and set the default variant.

## How To Test?
- Take a pull from the repo.
- Run `php artisan migrate` command.
- Go to the configurable product edit section.
- Select default variant.
- Last test in the frontend shop portion.

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 

- [ ] Variant selection is missing for the default theme.
- [ ] In Velocity, when adding configurable item directly from the homepage, the default selected item should be added to cart instead of showing a warning https://prnt.sc/165nvq5
- [ ] default selection is not clickable in RTL format eg; ar locale https://prnt.sc/165pg0y

**Comment by devansh-webkul** [comment]
On opening the opacity came to know that the radio button is slightly side by pixels so fixed that for perfection,

- Before

    Screenshot(1)

- After

    Screenshot

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

Mentioned changes have been completed.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
Default variant functionality is only working for select type swatch, Kindly fix this for text,color,image swatch type value https://prnt.sc/167fcpu

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Mentioned changes have been done.

**Review by vaishaliwebkul — APPROVED** [review]

**Comment by devansh-webkul** [comment]
Hi @ghermans,

Just only one case that needs to check as mentioned by @vaishaliwebkul. I will open it once that confirm.

**Comment by devansh-webkul** [comment]
The issue already found in the core,
https://github.com/bagisto/bagisto/issues/4959

So this PR is ready for merge.

**Pull request merged**
