### PR TITLE
Updated EN translation for activate-warning

### PR DESCRIPTION
**Pull request by ghermans**
## Description
`en` translation updated for `activate-warning`

image

### CODE REVIEW

**Comment by devansh-webkul** [comment]
Hello @ghermans,

Thank you so much for the contribution. :rocket:

**Comment by devansh-webkul** [comment]
Could you please update this pull request to target the 2.2 branch? Thank you! :innocent:

**Comment by ghermans** [comment]
done, @devansh-webkul

**Comment by devansh-webkul** [comment]
@ghermans,

Our branch is currently around 150 commits ahead. Please create a new branch from the 2.2 branch to resolve this.

**Pull request closed without merging**
