### PR TITLE
Issue Fixed #6860 (In Catalog Products, Weight should not be negative)

### LINKED ISSUE #6860: The product's weight can not be in a negative value
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Create a **configurable** product.
**3.** Add a negative value on the weight input field of any variant.

**Expected result:** The product's **weight** can not be in a **negative value**

**Actual result:** weight input box is taking a **negative value** if the admin is creating **configurable** products. please find the screenshot [Here](https://prnt.sc/b9eAxx32TrJP)

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference

Issue Fixed #6860 
## Description

Validation Updated in Weight Input field for Only Numeric 
## How To Test This?

Step to Test
1. Log in as an admin.
2. Create a configurable product.
3. Add a negative value on the weight input field of any variant.
## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
The product **weight** can **not** be **like 0.0,** and please **add** the same **validation** for **price** also, please find the screenshot [Here](https://prnt.sc/se6HHQthiRXk)

**Comment by JunaidJaved248** [comment]
Okay Sure @Sanjaybhattwebkul

**Comment by JunaidJaved248** [comment]
Okay Sure @Sanjaybhattwebkul

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Please check it out. Seems Good?
image

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Please **edit** any **variant/simpl**e product,then **reproduce**, please find the **screenshot** [Here](https://prnt.sc/hZQJxhvg-n5i)

**Comment by JunaidJaved248** [comment]
> @JunaidJaved248 Please **edit** any **variant/simpl**e product,then **reproduce**, please find the **screenshot** [Here](https://prnt.sc/hZQJxhvg-n5i)

@Sanjaybhattwebkul I checked the weight attribute in product regarding validation issue, Actually, In AttributeTableSeeder, Validation set for weight decimal. So, Thats why, 0.0 value added in weight input field.
I have two solutions for it, First, I have to make change in seeder of Attribute, Second one i have put hard check on weight attribute. Both will fixed the issue. Let me know, which solution one will be okay ?

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 

The **physical product's** weight can be a **decimal value**. so You can fix this issue by creating the **custom validation** with **greater than zero.**. Or By using  [Regex](https://stackoverflow.com/questions/8609714/regex-greater-than-zero-with-2-decimal-places).

Please take a **reference** from [Here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/rental.blade.php#L137) for creating the **custom validation**

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Any **update**?

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Working on it.

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Please check it out. Its also Done!!!

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
**Still not fixed**, please find the **screenshot** [Here](https://prnt.sc/GtSrGOPjazrw)
The product's weight **can be** a **float** value.

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Check now Please

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul You can check it now. Its fixed.

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Now this issue **is fixed**, please find the **screenshot** [Here](https://prnt.sc/nNTNr3mdQgsm)
**Thanks** for your **contribution**.

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
