### PR TITLE
Fixed variant images which are not visible in a sorted manner as uploaded in backend #4690

### PR DESCRIPTION
**Pull request by devansh-webkul**
# Bug
Link: https://github.com/bagisto/bagisto/issues/4690

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
the same issue is also exists in the shop package.

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

The mentioned issue has been fixed.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
In shop package, the variant image should visible first before parent images

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

The mentioned issue has been fixed.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
