### PR TITLE
`DataGrid` refactoring: updated & fixed all typings + usage of `LengthAwarePaginator`

### PR DESCRIPTION
**Pull request by funder7**
## Issue Reference
#5400

## Description
**Replaced:**
  - all references from `Collection` (wrong) to `Query\Builder`
  - `DataGrid` traits return `LengthAwarePaginator` instead of Collection
  - `DB` with `Eloquent` `Query\Builder` to comply with `LenghtAwarePaginator`
  - model string reference with ::class (enable IDE ctrl+click navigation + reference lookup)
  - addColumn (closures):
    - complex if/elseif blocks with switch case
    - simple if/else blocks with ternary operator (type safe)

**Documented:**
  - class properties / function attributes and return types
  - exceptions in `DataGrid` classes

**New / Other:**
  - class properties / functions attributes and return types
  - return type (string) in all Facades (whole project)
  - localization in `CategoryDataGrid`
  - cleared some duplicated localization keys
  
## How To Test This?
Just follow the regular installation process, and verify that DataGrid is working properly

## Documentation
- [ ] My pull request requires an update on the documentation repository.

(I'm not sure about this point)

### CODE REVIEW

**Comment by devansh-webkul** [comment]
I am also thinking of the same but didn't get time to do that, thanks for such a lovely PR. :rocket: 

I will check both PRs when all reaming pull requests gets merged.

**Comment by funder7** [comment]
No problem mate, I fully understand!

See you next time :-)

**Comment by devansh-webkul** [comment]
Hi @funder7,

For PHPDoc comment, please follow this pattern,
https://laravel.com/docs/8.x/contributions#phpdoc

`throw` should be separated by a new line as we are following Laravel. I know in most of the places these are missing but we are fully trying to follow Laravel conventions.

And also no need for additional comment after throwing as the error clearly signifies.

**Comment by funder7** [comment]
Ok @devansh-webkul, thanks for pointing it out, I will update the configuration. 
Do you know php cs-fixer? I'm not using it but probably it's the right solution to keep a common style among the contributors. 
I've found [this article](https://dev.to/ibrarturi/setup-php-cs-fixer-for-laravel-project-44nf) which includes the setup plus the configuration to follow Laravel conventions (it's a starting point, it can be modified in any case).

I'll fix the conflicts in the next days! Cheers

**Comment by devansh-webkul** [comment]
We are planning for Style CI. Although CS fixer is also good.

**Comment by devansh-webkul** [comment]
Reference: https://github.com/bagisto/bagisto/pull/5362#issuecomment-1007163673

**Pull request closed without merging**
