### PR TITLE
Fixed Checkout page issues.

### PR DESCRIPTION
**Pull request by suraj-webkul**
Checkout old version

### CODE REVIEW

**Comment by ashishkumar-webkul** [comment]
@amit-webkul @suraj-webkul 

Checked and found that when a guest user is checking out a product with different shipping address and confiming the shipment it is still selecting the billing address. Please check the video.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/73cc300a-d444-4236-8d23-d10a0938be6e

**Comment by ashishkumar-webkul** [comment]
@amit-webkul and @suraj-webkul 

checked and found that the checkout page is working fine for Guest and Logged in user. Please check the videos.

**Guest User**

https://github.com/bagisto/bagisto/assets/92721837/c8742197-fde4-4801-a75d-3d73407e7e9f


https://github.com/bagisto/bagisto/assets/92721837/e2f264b2-47e9-4ed1-ac56-f69c8d0d4eaf


**Logged In User**

https://github.com/bagisto/bagisto/assets/92721837/78ba01eb-1d73-439b-8c44-40584a0e91ce

**Review by jitendra-webkul — APPROVED** [review]

**Comment by DanVu1007** [comment]
Hi @jitendra-webkul,
It works very well.
Many thanks :D

**Comment by DanVu1007** [comment]
Hi @jitendra-webkul,
I saw an error when making checkout.
https://www.loom.com/share/8d09d73cc86c4c93b214389dc98bbe05 
it just loading and can't get next step.
Please help me fix it.
Thanks

**Pull request merged**
