### PR TITLE
#1745 - add codeception and example tests

### PR DESCRIPTION
**Pull request by bosix**
see #1754 for details

### CODE REVIEW

**Comment by bosix** [comment]
Hi @jitendra-webkul @shubhwebkul @rahulshukla-webkul ,

is this PR still in review? A few other issues are relying on it.

**Comment by bosix** [comment]
Hi @rahulshukla-webkul 

thank you for your review.

It seems like you already have some data in your database. I've extended the command `composer test`. It will run `php artisan migrate:fresh` before running tests to ensure having a clean database for testing.

Please try again and let me know if any other error occurs.

**Comment by bosix** [comment]
Hi @rahulshukla-webkul 

seeders will be automatically called by codeception. Have a look at `unit.suite.yml` and `functional.suite.yml`.

**Comment by bosix** [comment]
Hi @rahulshukla-webkul 

I've verified that data is seeded at my side by extending `ProductTypeCest`:

```
public function testHasVariants(UnitTester $I)
    {
        dd(InventorySource::all()->toArray());

        $I->assertTrue(ProductType::hasVariants('configurable'));
        $I->assertFalse(ProductType::hasVariants('simple'));
    }
```

Codeception wraps every test into a db-transaction. That's why you cannot see any data in the test-db via tools like phpmyadmin. It's because data is seeded every time a test is started to ensure each test has the same test-data. At the end of a test the transaction is reverted to get a nice and clean db for the next test.

**Comment by jitendra-webkul** [comment]
@bosix 

Thanks for your efforts much appreciated

**Pull request merged**
