### PR TITLE
Issue #3496 fixed

### PR DESCRIPTION
**Pull request by vishal-webkul**
**BUGS:**

Issue Id:- #3496 

**For things other than bugs:**

> Describe that thing in very short line, word limit is 200.
> Otherwise use **issue #id** if the issue was filed as **feature** request.

### CODE REVIEW

**Comment by bhanu-webkul** [comment]
@vishal-webkul 

As of now, if attribute label is not set for any particular locale, then while comparing products in that locale it should show by default label which is set to admin, 
https://prnt.sc/tmhdku
compare page- https://prnt.sc/tmhfhi

**Comment by vishal-webkul** [comment]
@bhanu-webkul 

It is a separate issue

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
Mentioned issue is resolve please let me know if there is any remaining

**Comment by bhanu-webkul** [comment]
@vishal-webkul 
Please check with localized attributes, for eg: there is no value in fr for that attribute -https://prnt.sc/tnxb86 still in compare list its showing value of en locale- https://prnt.sc/tnxbmh

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
It is different issue

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
Above mentioned issue fixed please let me know if there is any one remains.

**Comment by bhanu-webkul** [comment]
still i can see localized attribute value in different locale while comparing in which admin did not save any value for that attribute

**Comment by vaishaliwebkul** [comment]
@vishal-webkul 
kindly resolve conflicts

**Pull request closed without merging**
