### PR TITLE
Change the checkbox in dark mode

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#7196

https://webkul.chatwhizz.com/share/view-recording/63ece72793ea2803a944990f

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@abdulhamid-alattar 
**Not working**, and the **checkboxes** are **not visible** in dark mode, please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63edbbac93ea2803a944a272)

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Check Now

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Still not fixed**, the checkboxes are **by default** getting **selected** Please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63edd06993ea2803a944a9ba)

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Check Now

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Now, this is **working fine**,Please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63ee2719aac9534fac259906)

**Review by Sanjaybhattwebkul — DISMISSED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
This is **working fine**. please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63ee39cabf991905516b4a4f)

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
