### PR TITLE
Issue #3531 fixed

### PR DESCRIPTION
**Pull request by vishal-webkul**
**BUGS:**

issue: #3531 

**For things other than bugs:**

> Describe that thing in very short line, word limit is 200.
> Otherwise use **issue #id** if the issue was filed as **feature** request.

### CODE REVIEW

**Comment by bhanu-webkul** [comment]
@vishal-webkul 
Its not working properly if total is float like 329,45$US

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
Above mentioned issue solved please let me know if any other remains

**Comment by bhanu-webkul** [comment]
Not working - getting exception while using filter total column and applying other the equals to condition

Screenshot 2020-07-30 13:14:52

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
now fixed

**Comment by bhanu-webkul** [comment]
Now working

**Pull request merged**
