### PR TITLE
Fixed issue #6366

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#6366

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Not working,** still getting the same issue.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul In mine, it`s working please re-check

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
As we checked, the products are not listed in the shop. by this PR.

**Comment by Sanjaybhattwebkul** [comment]
Please check it again

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please **resolve** the **conflicts**

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Resolved

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
**Not working**, the products are showing on the home page.

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Any update?

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Recheck the issue

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
