### PR TITLE
Add various improvements for mobile nav

### PR DESCRIPTION
**Pull request by lex111**
## Description

- Expanding mobile nav to full viewport height (as it actually was before)
- Removing margin at the bottom of mobile nav
- UX improvements: hiding mobile nav when overlay is tapped and block mobile scroll when mobile nav is open
- Styles refactoring: switching to flexbox (for better vertical center alignment and avoid excess code), removing duplicate styles in dark/RTL modes. 

## How To Test This?

Open any admin page on mobile and tab to hamburger icon.

| Before   | After    |
| -------- | -------- |
| image | image |

## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@lex111 
Please **resolve** the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@lex111 
Still getting the **conflicts**.

**Comment by lex111** [comment]
Unfortunately I won't be able to resolve the conflicts next week as I don't
have access to my pc. So can you please regenerate the assets files?

вс, 16 окт. 2022 г., 5:44 Sanjaybhattwebkul ***@***.***>:

**Comment by lex111** [comment]
@Sanjaybhattwebkul conflicts resolved, sorry for the delay.

**Comment by lex111** [comment]
friendly ping for @jitendra-webkul and @Sanjaybhattwebkul.
Although I already have 4 merged PRs, I still wanted this PR to be merged as part of Hacktoberfest as well.

**Comment by lex111** [comment]
Please check it out again

**Comment by Sanjaybhattwebkul** [comment]
@lex111 
**Thanks** for your **contribution**

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by jitendra-webkul** [comment]
Functional tests are failing

**Comment by lex111** [comment]
How to fix these tests, since I don't really understand what's wrong with them?

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please check the **_CartTaxesCest.php_** file

**Comment by Sanjaybhattwebkul** [comment]
The **asserting** is Failed on the **_CartTaxesCest.php_** file, please find the **screenshot** [Here](https://prnt.sc/vHBdGHi2JZTb)

**Comment by lex111** [comment]
Does nothing for me. What does this have to do with my changes? I have only edited the HTML markup and CSS.

**Comment by jitendra-webkul** [comment]
@lex111 It's the functional test, it looks for the Html tags if the page has an element with a certain class, etc. I think you have changed some HTML that causes the failure. You can check the failed pipeline to check the issues

**Comment by devansh-webkul** [comment]
Hi @lex111,

Conflictions and test cases are failing. Please check.

**Comment by lex111** [comment]
Since I still don't understand how to fix the tests, and I don't think anyone can help me with that, I'd better close this PR.

**Pull request closed without merging**
