### PR TITLE
Alignment Fixed #4570

### LINKED ISSUE #4570: Bliss | Add to Card button not aligned
# Bug report

### Title
Add to Card button is not aligned in the product listing.

### Issue Description
Add to Card button is not aligned in the product listing. They should sync irrespective of the product title length.

The issue is similar to the link below. However, this is only done in velocity. I want it to be done in Bliss.
https://github.com/bagisto/bagisto/issues/4114
 
### Preconditions
    1. version v1.2.0

### Steps to reproduce
1. step1- add some products with special price

### Expected result
alignment should be equal for all product.

### Actual result

image

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4570

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
could you please fix the alignment for product view when change the category page to **list mode**

actual result https://prnt.sc/ypn3h2
expected result https://prnt.sc/ypn5sj

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Mentioned changes has been done.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
after getting the above changes,  compare page alignment changed. https://prnt.sc/ypw0wc

expected https://prnt.sc/ypwchl

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

The mentioned changes have been done.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
