### PR TITLE
Paypal refund feature added

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Enhancement
- Added PayPal refund feature.

## Code additions
- `Order` listener class got too bulky with mails so organized all mails in a trait named `Mails`.
- On creating order saved additional data to the table.
- Fixed capture id bug in the Paypal smart button.
- Added easy executable methods to the `SmartButton` class for easy calling.

## Steps to execute this pull request
- Run `php artisan migrate`.
- Run `php artisan optimize`.

### CODE REVIEW

**Review by rahulshukla-webkul — CHANGES_REQUESTED** [review]
Unable to Process for order when using two currency.-https://prnt.sc/yyogxp

**Comment by devansh-webkul** [comment]
Hi @rahulshukla-webkul,

This seems to be the problem with sandbox accounts. As accepted currency can only be possible if a business account is holding.
Link 1: https://developer.paypal.com/docs/api/reference/currency-codes/
Link 2: https://developer.paypal.com/docs/api/reference/currency-codes/#payment-receiving-preferences

If business account location is set to the US, then in the backend only the US should be there. So accepted currency should be matched with business account's country.

**Review by rahulshukla-webkul — CHANGES_REQUESTED** [review]
Hi @devansh-webkul 

Getting exception when clicking on refund - https://prnt.sc/z6ynje

**Comment by devansh-webkul** [comment]
Hi @rahulshukla-webkul,

Just need to run `php artisan migrate` for an additional column and then re-order the product.

**Review by rahulshukla-webkul — APPROVED** [review]

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
