### PR TITLE
[Fixed Issue #553: Related to Country list and remove extra double quote in data-vv-as.]

### PR DESCRIPTION
**Pull request by vivek-webkul**

### CODE REVIEW

**Comment by prashant-webkul** [comment]
That was not extra double quote '&quot' was intended to show up on frontend, check screenshot below.
In screenshot you can see '**"color"**' in quotes, so that '&quot;' is doing that:

quot

**Comment by vivek-webkul** [comment]
@prashant-webkul Ok revert those changes.

**Comment by vivek-webkul** [comment]
@prashant-webkul :- There was another issue too. Which i mentioned in point 1.

**Comment by vivek-webkul** [comment]
https://github.com/bagisto/bagisto/pull/554/files#diff-253132688c3cc6865a5bdeabef224da6R225

**Comment by prashant-webkul** [comment]
Will be fixed in next update or release

**Pull request closed without merging**
