### PR TITLE
Fixed getting exception when view order of deleted customer #3422

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3422

### CODE REVIEW

**Comment by bhanu-webkul** [comment]
on deleting customer Error message should be like this - https://prnt.sc/tr3qlm

**Comment by bhanu-webkul** [comment]
customer is getting deleted using mass action delete option even if there is pending /processing order

**Comment by vaishaliwebkul** [comment]
- alert message on customer end is incorrect https://prnt.sc/ttpz9m

- getting exception when view refund for delete customer
Screenshot_5

**Comment by vaishaliwebkul** [comment]
working fine

**Pull request merged**
