### PR TITLE
Fixed #8605 (Currency Code also not showing when its removed from admin panel)

### LINKED ISSUE #8605: After deleting the currency symbol. still, it is showing in the Shop.
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

After deleting the currency symbol. still, it is showing in the Shop.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one currency.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit currency' inside the Settings/Currency
3. Delete the currency symbol and save it.
4. Go to the Shop
5. See the error

### Expected Result

It should show the currency code instead of the deleted symbol.

### Actual Result

Still shows a currency symbol instead of a currency code. [Here](https://prnt.sc/990bCjvJNFHA)

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference
#8605 

## Description
Fixed it, via checking if $currency->symbol is empty, then its Setting Symbol for Currency empty

## How To Test This?
Go to 'Admin panel'
Click on 'Edit currency' inside the Settings/Currency
Delete the currency symbol and save it.
Go to the Shop
## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by JunaidJaved248** [comment]
@devansh-webkul Update also about it, is it considerable?

**Comment by JunaidJaved248** [comment]
@devansh-webkul Can You update on this pull request?

**Comment by JunaidJaved248** [comment]
@devansh-webkul Any update on it ?

**Comment by devansh-webkul** [comment]
We will check this internally, as there are some core classes refinement done today.

**Pull request closed without merging**
