### PR TITLE
Updated the cart as price updated by Admin 

### PR DESCRIPTION
**Pull request by akathuria289**
## Issue Reference
#7378

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The product's price should be updated, after applying the discount. please find the screenshot [Hee](https://webkul.chatwhizz.com/share/screenshot/64255ab92a666707c400fbf9)

_**Note :**_  _**Discounts can be like Catalog Rule, SPecial price, Customer Group Price.**_

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
If admin applies the **special price** and the search mode is **product-flat**. the product price is n**ot updated**. Please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/642586672a666707c401a5ad)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Getting the same issue for group products. Please find the screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/6433e85383d74a61f23f229b)

**Comment by devansh-webkul** [comment]
@Amitk-webkul,

Please check this.

**Comment by Amitk-webkul** [comment]
@akathuria289 
If the search mode flat table is selected and the products have a special price applied so the price is not changing in the mini cart. [Here](https://prnt.sc/R8oihPTIx6jF)

**Pull request closed without merging**
