### PR TITLE
Fix bug action datagrid filters page customer

### PR DESCRIPTION
**Pull request by KarimQaderi**
fix bug in page like 127.0.0.1:8000/customer/account/orders

### CODE REVIEW

**Comment by ghermans** [comment]
@KarimQaderi thank you for your pull request we really appreciate this, still i would like to ask you the following two items:

1. Can you provide more details about this PR / use the pull request template.
2. In case a bug exist within Bagisto, please also [create a issue report](https://github.com/bagisto/bagisto/issues/new/choose) for it

**Comment by devansh-webkul** [comment]
Hi @KarimQaderi 

This is not needed as `title` is mandatory while providing action array.

**Comment by KarimQaderi** [comment]
# Bug report

### Issue Description
In the front section of the customer pages, the type of grid is different and the operations of that section have no title and cause errors.

### Preconditions

    1. 8.0
    2. 6a3e5c539fc816e54b087ca4d8d4ed76c3b1d60b

### Steps to reproduce

    1. Go to account
    2. Select orders

### Expected result
image


### Actual result

image

**Comment by devansh-webkul** [comment]
Hi @KarimQaderi 

Problem lies in the customer action datagrid just provide title there and it will work as expected and i will update the docs also.

If you want you can do PR also.

**Comment by KarimQaderi** [comment]
> Hi @KarimQaderi
> 
> Problem lies in the customer action datagrid just provide title there and it will work as expected and i will update the docs also.
> 
> If you want you can do PR also.

Hi

Ok me add title for actions

**Comment by devansh-webkul** [comment]
If you check the admin portion all datagrids are having title key may be title key got missed in the customer section thats why its not getting triggered till your previous PR.

**Pull request closed without merging**
