### PR TITLE
Add common error. md file and provide solution

### PR DESCRIPTION
**Pull request by Mahendra-24**
found Error during Authentication and UI installation

### CODE REVIEW

**Comment by shubhwebkul** [comment]
Hi @Mahendra-24 
please resolve conflicts

**Comment by shubhwebkul** [comment]
Please make sure you change only relevant files. you can also checkout [here](https://github.com/bagisto/bagisto/pull/3151/files)

**Comment by Mahendra-24** [comment]
Sir, I  have resolved all the conflicts and make a new branch for that.

**Comment by shubhwebkul** [comment]
there are still conflicts, please resolve those.

Also, mention what is the motive of this PR

**Pull request closed without merging**
