### PR TITLE
Varient image issue fixed

### PR DESCRIPTION
**Pull request by shivendra-webkul**
## Issue Reference
#7136

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@shivendra-webkul 
**Not working**. please find the screenshot [Here](https://prnt.sc/B51s8TADOpWl)

**Comment by shivendra-webkul** [comment]
add image button issue fixed
issue add image

**Comment by Sanjaybhattwebkul** [comment]
@shivendra-webkul 
**Not working,** please recompile your files. run the given commands
1. _**npm i**_ 
2. **_npm run prod_**

**Comment by Sanjaybhattwebkul** [comment]
@shivendra-webkul 
Still **not fixed**, Please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63ea144193ea2803a9440871)

**Comment by shivendra-webkul** [comment]
@Sanjaybhattwebkul  
Issue fixed, Please find the screenshot here
var

**Comment by Sanjaybhattwebkul** [comment]
@shivendra-webkul 
**Getting ui issues** while trying to upload **multiple images** of a product. Please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63f368dfaac9534fac261355)

**Comment by Sanjaybhattwebkul** [comment]
@shivendra-webkul 
This is **working fine**,

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Comment by Sanjaybhattwebkul** [comment]
@shivendra-webkul 
Resolve the **conflicts**

**Comment by shivendra-webkul** [comment]
New PR for this issue find link here.
https://github.com/bagisto/bagisto/pull/7349/files

**Pull request closed without merging**
