### PR TITLE
Checkbox Support Added To Datagrid #6241

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Issue Reference
Link 1: https://github.com/bagisto/bagisto/issues/6241
Link 2: https://github.com/bagisto/bagisto/issues/6270

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
The selected option should be visible. Please take a reference from [Here](https://prnt.sc/Vmwnt-aeGke0).

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
The status filter is working only in the English language.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
There should be proper alignment in the Arabic locale. Please find the screenshot [Here](https://prnt.sc/vkGGMNsv7cI-)

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
The translation is missing for the filtered value. please find the screenshot [Here](https://prnt.sc/Cdkbrhk-CKOb).

**Comment by devansh-webkul** [comment]
Checking

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Pull request merged**
