### PR TITLE
Rework and fix anchors in README

### PR DESCRIPTION
**Pull request by adpe**
Just a set of corrections

### CODE REVIEW

**Comment by adpe** [comment]
Hi @rahulshukla-webkul 

On my branch I see that all it's working. Can you provide an image what's missing?

**Comment by rahulshukla-webkul** [comment]
Hi,

Please see this - https://prnt.sc/oclqgi.

**Comment by adpe** [comment]
It is like that? That's not good?

image

**Comment by rahulshukla-webkul** [comment]
Hi @adpe 

Contributors & Backers are two different things, we can't  show them like this.

**Comment by adpe** [comment]
Hi

I've now made your suggested changes.

Greets,
Adrian

**Comment by jitendra-webkul** [comment]
@adpe 

Thanks

**Pull request merged**
