### PR TITLE
add greek translation

### PR DESCRIPTION
**Pull request by nextdoorpanda**
Hi!

## Issue Reference

#6909 

## Description

I've added the Greek translation

## Documentation
- [ ] My pull request requires an update on the documentation repository.

Happy hacktoberfest! 😁

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please add the translation for the **following** packages **too**.

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Admin/src/Resources/lang/

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Core/src/Resources/lang/

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Shop/src/Resources/lang/

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Velocity/src/Resources/lang/

**Comment by nextdoorpanda** [comment]
> 

Sure!

**Comment by Sanjaybhattwebkul** [comment]
@nextdoorpanda 
The **validation** errors are **not translating,** please find the screenshot [Here](https://prnt.sc/qtndRiELOV78)

**Comment by nextdoorpanda** [comment]
> @nextdoorpanda The **validation** errors are **not translating,** please find the screenshot [Here](https://prnt.sc/qtndRiELOV78)

I'll check it out! Are the validation errors' strings inside of one of the 4 packages that pending translations (the packages that you mentioned in your previous comment)?

**Comment by Sanjaybhattwebkul** [comment]
@nextdoorpanda 
Please add locale [Here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/assets/js/app.js#L21-L37) also

**Comment by Sanjaybhattwebkul** [comment]
@nextdoorpanda 
The **validation** warnings are **still not translating**, Please find the **screenshot** [here](https://prnt.sc/K0kaKjbMt4_9)

**Comment by nextdoorpanda** [comment]
@Sanjaybhattwebkul Thank you for informing me about it. I already know it, I haven't been able to fix it because I am extremely busy these days! I'll let you know when it is fixed!

**Comment by nextdoorpanda** [comment]
Could you please test it again?

**Comment by Sanjaybhattwebkul** [comment]
@nextdoorpanda 
**Still not fixed** properly, please find the **screenshot** [Here](https://prnt.sc/baDeFrXwZwqa)

**Comment by Sanjaybhattwebkul** [comment]
Closing this pull request as no activity from the **last months.**

**Feel free** to open a new pull request once done.

**Pull request closed without merging**
