### PR TITLE
fix for issue #8556

### PR DESCRIPTION
**Pull request by codeinnovers**
## Issue Reference
Fix for issue #8556
## Description

Changed the default value to 0 for the associated hidden field for is_required field.
Also commented the disabled option for is_required checkbox assuming user can change the option at later stage.
### Test Case 1
1. Create the attribute , check is_required and save the attribute
2. Edit the attribute, save it without any changes.
3. Edit the attribute again and is_required should still be checked
### Test Case 2
1. Create the attribute , check is_required and save the attribute
2. Edit the attribute, uncheck the is_required checkbox, save it.
3. Edit the attribute again and is_required should be  un-checked

### CODE REVIEW

**Comment by devansh-webkul** [comment]
Hi @codeinnovers,

These issues are already fixed in our system. I am closing this. Please select valid issues and assign yourself first to avoid work duplicacy. 

Thanks!

**Comment by codeinnovers** [comment]
Hello @devansh-webkul 
The task was assigned to me before I started to work.

**Comment by devansh-webkul** [comment]
Let me verify it because due to so many PRs, it may get fixed from somewhere else.

**Comment by codeinnovers** [comment]
no worries. what matters is the issue is fixed.

**Pull request closed without merging**
