### PR TITLE
Spanish translation for Shop module

### PR DESCRIPTION
**Pull request by marcmascarell**

### CODE REVIEW

**Comment by prashant-webkul** [comment]
@marcmascarell Really nice work. Can you increase your scope of work in Admin and Ui package as well.

**Comment by prashant-webkul** [comment]
@prateek-webkul Please check the file changes.
@jyoti-webkul Please test this branch for spanish.

**Comment by marcmascarell** [comment]
@prashant-webkul Im working on it. But as you may know there are many to translate so it will take a while.

**Comment by prashant-webkul** [comment]
> @prashant-webkul Im working on it. But as you may know there are many to translate so it will take a while.

No problem, take as much time as you want.

**Pull request merged**
