### PR TITLE
Issue fixed #7136

### LINKED ISSUE #7136: UI issue in mobile inspect and Desktop view -> Configurable product variants add section.
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we create a Configurable product and add  variant details, there we can see the UI issue in the Add image section. weather we add a single  image or multiple image we can see that the UI issue is still appearing. Checked the issue in the mobile view and desktop view.

### Preconditions

1. Admin end should work properly.
2.  Able to create a Configurable product.

### Steps to reproduce

1. Go to Admin -> Catalog -> Product -> Create a configurable product.
2. Now in the variants section add the details and images.
3.  Check the UI of the variants image section in Mobile View and Desktop View.
4.  There we will be able to see the UI issue.

### Expected Result

The Variants images should be clear and there should be no overlapping in the Delete button in mobile view.
All the images delete button should be in proper place. 
In Desktop View and Mobile Inspection view the details should appear clear.

### Actual Result

Please check the screenshots for a better understanding of the issues. Please check for the reference.

### Screenshots

**Desktop View**

Desktop View

**Mobile View**

Mobile view

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by prabhatkumaroc082**
Fixed #7136

### CODE REVIEW

**Comment by Nikitajoshi39** [comment]
@prabhatkumaroc082 Still getting  this issue  screenshot [here](https://prnt.sc/9WB-1k1IQvTC)

**Comment by prabhatkumaroc082** [comment]
@Nikitajoshi39 explained [here](https://github.com/bagisto/bagisto/issues/7136#issuecomment-1328025349), no need to adjust the content. vertical alignment is applied to middle. 

let me know if any issue with image responsive.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
All the input boxes should be in **alignment**, please take a **reference** from [Here](https://prnt.sc/cD1smAAYqjVm)

**Comment by prabhatkumaroc082** [comment]
@Nikitajoshi39 @Sanjaybhattwebkul review the alignment now.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Getting **unnecessary space** if trying to upload multiple images of 1 product.

**Comment by Sanjaybhattwebkul** [comment]
Please find the screenshot [Here](https://prnt.sc/OA3yI8au09f4)

**Comment by prabhatkumaroc082** [comment]
> Please find the screenshot [Here](https://prnt.sc/OA3yI8au09f4)

@Sanjaybhattwebkul inline-block is already set, delete icon is also taking some space, it will auto-adjust as per device width.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
I am getting the issue in desktop.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Please take a **reference** for the below Image to **improve** the **variants section** of the configurable product.

image

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Please resolved the **conflicts**.

**Comment by prabhatkumaroc082** [comment]
@Sanjaybhattwebkul review now.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Please **improve** the **add image** icon. please take a **reference** from [here](https://prnt.sc/1q9OQWLU1nU5)

**Comment by prabhatkumaroc082** [comment]
@Sanjaybhattwebkul added [camera icon](https://user-images.githubusercontent.com/50438561/205884797-9ca2b83c-0547-4681-ab26-e8f183fd7754.png)

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Please **resolved** the **conflicts**.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
**Still not as accepted**, please find the **screenshot** [Here](https://prnt.sc/ThU0H973Aqx8)

**Comment by prabhatkumaroc082** [comment]
@Sanjaybhattwebkul 
updated assets, review again. here are some screenshots [image1](https://user-images.githubusercontent.com/50438561/207828628-b6c9a58d-7b09-4936-ad9e-30a84e441d61.png), 
[image2](https://user-images.githubusercontent.com/50438561/207829999-16fef740-0e92-4079-98de-cbd3b32b416d.png]()

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Please do the same for the **Add Link** section of the **downloadable** product. Please find the screenshot [Here](https://prnt.sc/ZBxsC_3PTxPq)

**Comment by prabhatkumaroc082** [comment]
@Sanjaybhattwebkul please review now the table fields of each page.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
The **textbox** UI issue is **fixed now,** but the **added image** options are **not as expected**. Please take a **reference** from [Here](https://prnt.sc/hwLq2lyVyaI1) for the add image section.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
The new box **should not appear** after clicking on **add image section**, If the admin is clicking on the add image option then the window should be opened to select the image.

**Comment by Sanjaybhattwebkul** [comment]
Closing this PR as not getting any response from the last 2 months.

**Pull request closed without merging**
