### PR TITLE
Fixed order cancel option is not coming even if invoice state is pending #3679

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3679

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
working now

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
kindly check when invoice status is paid and order status is processing still cancel is visible https://prnt.sc/tzi8jc

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
generated invoice status is not visible in the order summary https://prnt.sc/tzkvhm

**Comment by devansh-webkul** [comment]
This PR is not valid for existing Orders. Instead I am opening alternate one please check.

**Pull request closed without merging**
