### PR TITLE
Feature : New issue templates with .yml files 🛠

### LINKED ISSUE #6810: Updates : New issue templates using .yml instead of .md 🛠
## What i am suggesting to update ? 

I am suggesting to update the Issue templates , currently we are using `.md` files instead of the brand new issue forms with `.yml` files which makes it more easier to fill in the data and raise an issue !

## Why to update it ? 

Adding an issue Template allows you to organize the issues made by folks in a much better way.
 - We can know if someone wants to write a test or maybe fix something in the website
 - The issue template forms makes writing details more efficient and quick
 - Also since there are `required` options, you can never miss on important values !
 - Here's a general idea : 

image

image

## Can i work on it ? 

Yes, i will be glad to help an Opensource project grow more !

### PR DESCRIPTION
**Pull request by IAmTamal**
## Issue Reference

My PR closes #6810 

## Changes requested : 

- i have asked to add Issue templates in the repository using `.yml` files.
- There must be same fields as there already was in the `.md` files !
- I am working to close #6810 

## Changes made

- 2 new `.yml` files were added to the `ISSUE_TEMPLATE` directory
- Issue templates with the same labels, fields are added as there was previously in the `.md` files.
- Some fields are made `required` so that it is compulsory to add data to those fields !
- Blank issues are kept `false` as  it was.

## Screenshots of the new templates : 

image

image

## How To Test This?

Just visit the [Forked version](https://github.com/IAmTamal/bagisto) and try out making an  issue !

## Documentation
- [ ] My pull request requires an update on the documentation repository.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@IAmTamal 
Please add the **input box** for Bagisto **versions**, please take a **reference** from [Here](https://prnt.sc/jG1wPi5cAvnx)

**Comment by IAmTamal** [comment]
@Sanjaybhattwebkul  So do i remove the checkboxes for the versions and add the `input` ? 
image

OR Add both ?

**Comment by Sanjaybhattwebkul** [comment]
Yes

**Comment by IAmTamal** [comment]
> Yes, replace checkboxes with input box.

image

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
