### PR TITLE
Fixed #3874

### LINKED ISSUE #3874: variant options are not added in wishlist in velocity theme
# Bug report

### Title
variant options are not added in wishlist in velocity theme

### Issue Description
When move variants to wishlist from the cart page, the only main product is visible in wishlist instead of variants

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add configurable products variants in cart
    2. step2- go to cart & move to wishlist cart items added as variants

### Expected result

variant option should be visible
Screenshot_46

### Actual result

In velocity variant options are not visible
Screenshot_47

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Issue 1: https://github.com/bagisto/bagisto/issues/3874
Issue 2: https://github.com/bagisto/bagisto/issues/3949

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
move to cart button is missing https://prnt.sc/uayzyy

**Comment by vaishaliwebkul** [comment]
implement this for guest user as well, also remove the delete button from the wishlist https://prnt.sc/ubbee3

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
guest user wishlist is not loading
Screenshot_72

**Comment by devansh-webkul** [comment]
@vaishaliwebkul 

Its working fine from my end. Please take a pull again may be you are not getting full changes.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
need to fix all the below cases in case of guest or logged in user

- item with variant or item without variants should be added in the wishlist eg. 
- when moving to cart only item without having any variant then other product(with variant) should not be removed from the wishlist
- In case of logged-in user, when we move the variant from the cart then already added wishlisted item(directly added from home page) should not replaced.

Note: all the above points should work in case of auth user as well as guest user.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
options are coming now but not visible properly because of cart layout, we should show the wishlist item in the list layout.
https://prnt.sc/uuq092

**Comment by vaishaliwebkul** [comment]
fix pagination https://prnt.sc/uvcwpf

**Comment by vaishaliwebkul** [comment]
done

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
