### PR TITLE
Fix Quantity Issue While Moving Product From Cart To Wishlist.

### PR DESCRIPTION
**Pull request by amit-webkul**
## Issue Reference
We have an issue with product quantity when we first add a product to the wishlist, then increase the product quantity and move it to the cart for that particular selected product. After that comes to the cart, the same quantity or updated quantity of the product moves to the wishlist. Then, inside the wish list, we have an error on product quantity.

### CODE REVIEW

**Comment by ashishkumar-webkul** [comment]
@amit-webkul 

There are some test cases which are failed. Kindly check them and update accordingly.

**Comment by ashishkumar-webkul** [comment]
@amit-webkul 

Checked and Found that the issue has been fixed. Still there is an issue which is remaining. When we are adding any product directly to wishlist we are getting errors in console. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/82bd3b10-ed1d-4d93-a245-8a1f711d34ad

**Comment by ashishkumar-webkul** [comment]
@amit-webkul 

There are some test cases which are failed. Kindly check them and get them fixed.

**Comment by amit-webkul** [comment]
> @amit-webkul
> 
> There are some test cases which are failed. Kindly check them and get them fixed.

It has now passed all the test cases.

**Pull request closed without merging**
