### PR TITLE
Issue #4571 fixed.

### PR DESCRIPTION
**Pull request by rahulshukla-webkul**
Issue #4571 fixed.

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@rahulshukla-webkul 
In reference to issue #4571 => parent image and video is also visible in variant https://prnt.sc/yxomm7

**Comment by vaishaliwebkul** [comment]
@rahulshukla-webkul 
when we switch the variant in which video exist to another variant in which no video exist, having an issue
please see the attachment
https://www.loom.com/share/f40ac4b9460e48ac8ec1cf9334586c12

**Comment by rahulshukla-webkul** [comment]
Hi @vaishaliwebkul 

This is issue is not associated with this PR, kindly raise it separately.

**Comment by vaishaliwebkul** [comment]
@rahulshukla-webkul Okay got it,

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
