### PR TITLE
adding some part of social login feature

### PR DESCRIPTION
**Pull request by prashantsingh2408**
**ADDING SOCIAL LOGIN**

>The customers can now log in using their existing social networking credentials from Google , Facebook and other. The customers won't have to create a new account/sign up to the store to buy products.  The guest user can also use the social login option to complete the checkout process.

### CODE REVIEW

**Comment by prashantsingh2408** [comment]
Hi, I am adding some part of code to implement the social login feature.

**Comment by shubhwebkul** [comment]
@prashantsingh2408 ,

Thanks for your contribution, please add these changes inside core package.

**Comment by prashantsingh2408** [comment]
> Have we done any changes in UI for a customer, from where customer will login via any social platform ?
https://github.com/bagisto/bagisto/pull/3145#pullrequestreview-430311100
No, not up to now but I am working on it.
I want to add this type of code
```
<a href="/redirect"  class="btn btn-secondary btn-block">Sign in with Google</a>
```
There is some doubt because I am new to bagisto. Am I need to add code to this file to create a UI button for social login ?
**packages\Webkul\Velocity\src\Resources\views\shop\layouts\top-nav\login-section.blade.php**

**Comment by shubhwebkul** [comment]
#3367

**Pull request closed without merging**
