### PR TITLE
:sparkles: [master] feat: laravel 11 compatibility

### PR DESCRIPTION
**Pull request by devansh-webkul**
## Info
- Laravel 11 Compatibility

### CODE REVIEW

**Comment by ashishkumar-webkul** [comment]
1. Issue in Receiving Mails
Checked and found that when QUEUE_CONNECTION=database
and also php artisan queue:work has been set in backround, still mails are not received.
Screenshots -> https://prnt.sc/5zLxTjQQur_N, https://prnt.sc/LKMcwiG1avcp, https://prnt.sc/pS-vKavR9Xsg

2. Category Page List View is not working
Screenshot -> https://prnt.sc/zJKEAsLmj13C

**Comment by ashishkumar-webkul** [comment]
Getting 500 Internal Server Error in the Sitemap generation but when we refresh the page we can see that the sitemap is generated.

https://github.com/user-attachments/assets/1eae7737-3d36-4a8d-b7bc-0898d5f6048b

**Comment by ashishkumar-webkul** [comment]
Checked and found Email are being received.

https://prnt.sc/zUCDmclWdd18

**Comment by ashishkumar-webkul** [comment]
Checked and Found List and Grid view is working fine.

Screenshot from 2024-10-28 13-37-22
Screenshot from 2024-10-28 13-37-24

**Comment by ashishkumar-webkul** [comment]
Checked and found that the sitemap is working fine. Please check the video for reference.

**Video**

https://github.com/user-attachments/assets/12cae95e-4d96-4d36-83cd-e11a40f1426f

**Review by ashishkumar-webkul — APPROVED** [review]
@devansh-webkul 

I have checked every possible section with Laravel and found working fine, all the doubts which are appeared are cleared and found working as well.

-> Checked in Multi-channel.
-> Checked in Multi-currency.
-> Checked in Multi-locale.
-> Checked in Each and Every Section of the Bagisto End to End.
-> Found some  issues and which are raised and fixed.
-> Checked Each Configurations and  Settings from Admin Panel.
-> Checked the details in Multiple Inventory Sources for Inventory Management.
-> Checked the Products details and filters in Admin End.
-> Checked the Shop Front of Both the channels and found working.
-> Checked the Sales , orders and found it working.

**Comment by arturslogins** [comment]
When you plan to merge this in master?

**Pull request merged**
