### PR TITLE
Bullets visibility for product quick view #6365

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#6365 

## Description
Bullets visibility for product quick view popup.

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please resolved the **conflicts**

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 
conflicts resolved please check.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
This is **working fine**, please find the screenshot [Here](https://prnt.sc/j5AssG8XyCBu)

**Comment by papnoisanjeev** [comment]
Closing due to conflicts, separate PR #6593 request created.

**Pull request closed without merging**
