### PR TITLE
Fixed sort by newest first or oldest first doesn't work in category #4299

### PR DESCRIPTION
**Pull request by devansh-webkul**
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4299

### CODE REVIEW

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
oldest_first filter is not working when the open new category page & works fine when filter again by oldest first

**Comment by devansh-webkul** [comment]
I thought it was due to the default config. But from my end, it's working fine, I need the exact case in which it's failing.

### Default Selection

default

### From Select Option

on-select

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
run php artisan db:seed , to check default store configuration which is (sort by Z to A), now go to the category page here oldest first is select by default.

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Then in this case only adjusting the front end select option.

**Review by vaishaliwebkul — APPROVED** [review]

**Pull request merged**
