### PR TITLE
Invoice design updates #6838

### PR DESCRIPTION
**Pull request by papnoisanjeev**
## Issue Reference
#6838

## Description
**Before:**
https://user-images.githubusercontent.com/86394952/194283106-8c1d3e81-c057-4ec8-8189-e505a1d62135.png

**After:**
Aligned logo to centre position, Shifted some part of data on right side and used blank space here, 
Which will reduce page length and cover most of the data into a single page.
https://tinyurl.com/2lgvp692

### CODE REVIEW

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The invoice of the admin panel is not improved. please improve for admin panel also.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Getting some **translation** issues on invoice after **downloading**. please find the screenshot [Here](https://prnt.sc/d60uRmkl5ZM9)

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
The invoice logo's width and hieght still not good, please find the screenshot [Here](https://prnt.sc/i6kz_uqWRqKS)

**Comment by papnoisanjeev** [comment]
> @papnoisanjeev The invoice logo's width and hieght still not good, please find the screenshot [Here](https://prnt.sc/i6kz_uqWRqKS)

Logo height and width is fixed (70px) so need to upload  same size logo from admin panel.

**Review by Sanjaybhattwebkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]

**Pull request merged**
